[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/108232552",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-108232552",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 108232552,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-06-03T07:39:07Z",
    "updated_at": "2015-06-03T07:39:07Z",
    "body": "Which operating system are you using? And have you tried v0.27.2?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/108493692",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-108493692",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 108493692,
    "user": {
      "login": "kabalage",
      "id": 7619177,
      "avatar_url": "https://avatars0.githubusercontent.com/u/7619177?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kabalage",
      "html_url": "https://github.com/kabalage",
      "followers_url": "https://api.github.com/users/kabalage/followers",
      "following_url": "https://api.github.com/users/kabalage/following{/other_user}",
      "gists_url": "https://api.github.com/users/kabalage/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kabalage/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kabalage/subscriptions",
      "organizations_url": "https://api.github.com/users/kabalage/orgs",
      "repos_url": "https://api.github.com/users/kabalage/repos",
      "events_url": "https://api.github.com/users/kabalage/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kabalage/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-06-03T15:49:59Z",
    "updated_at": "2015-06-03T15:49:59Z",
    "body": "Yes, the issue is still there in `v0.27.2`. I'm using Ubuntu 14.04\n\nAlso there's an error that does not appear in case#2 (described above) besides the sandbox error, here is the log of case#1:\n\n```\n[11658:0603/173841:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.\napp ready\ninitSocket\n[11679:0603/173841:ERROR:sandbox_linux.cc(340)] InitializeSandbox() called with multiple threads in process gpu-process\nconnect_error { '0': 'timeout' }\nconnect_timeout { '0': 1000 }\nreconnect_attempt { '0': 1 }\nreconnecting { '0': 1 }\nconnect_error { '0': 'timeout' }\nreconnect_error { '0': 'timeout' }\nconnect_timeout { '0': 1000 }\n...\n```\n\nand here is case#2:\n\n```\n[11887:0603/174416:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.\ninitSocket\napp ready\nelectronReady\n```\n\nbefore `electronReady` it hangs for about 25 seconds, messaging with the app after this works.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/108916525",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-108916525",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 108916525,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-06-04T14:35:04Z",
    "updated_at": "2015-06-04T14:35:04Z",
    "body": "Looks like a bug of the uv message loop integration, but socket.io-client has too many abstractions around the actual call, I can not find out the root cause.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/180770361",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-180770361",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 180770361,
    "user": {
      "login": "leyenda",
      "id": 394050,
      "avatar_url": "https://avatars1.githubusercontent.com/u/394050?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/leyenda",
      "html_url": "https://github.com/leyenda",
      "followers_url": "https://api.github.com/users/leyenda/followers",
      "following_url": "https://api.github.com/users/leyenda/following{/other_user}",
      "gists_url": "https://api.github.com/users/leyenda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/leyenda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/leyenda/subscriptions",
      "organizations_url": "https://api.github.com/users/leyenda/orgs",
      "repos_url": "https://api.github.com/users/leyenda/repos",
      "events_url": "https://api.github.com/users/leyenda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/leyenda/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-02-06T14:04:56Z",
    "updated_at": "2016-02-06T14:04:56Z",
    "body": "+1 | This keeps happening on linux(tested on ubuntu 15.10 and raspbian), on windows it works fine. Im using electron 0.36.0 and for socket.io and socket.io-client 1.4.5.\n\nBut now it doesnt even show a timeout, Chromium show the websockets  with a 101 status and keeps opening more and more sockets but no data can be transfer.\n\nSocket.io-client keeps working alone on linux, but not with electron.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/220188209",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-220188209",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 220188209,
    "user": {
      "login": "andresmeidla",
      "id": 8395526,
      "avatar_url": "https://avatars1.githubusercontent.com/u/8395526?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/andresmeidla",
      "html_url": "https://github.com/andresmeidla",
      "followers_url": "https://api.github.com/users/andresmeidla/followers",
      "following_url": "https://api.github.com/users/andresmeidla/following{/other_user}",
      "gists_url": "https://api.github.com/users/andresmeidla/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/andresmeidla/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andresmeidla/subscriptions",
      "organizations_url": "https://api.github.com/users/andresmeidla/orgs",
      "repos_url": "https://api.github.com/users/andresmeidla/repos",
      "events_url": "https://api.github.com/users/andresmeidla/events{/privacy}",
      "received_events_url": "https://api.github.com/users/andresmeidla/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-05-18T23:29:49Z",
    "updated_at": "2016-05-18T23:29:49Z",
    "body": "The error happens to this setup also:\nUbuntu 16.04, electron  0.37.0, socket.io-client 1.4.6\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/220196388",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-220196388",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 220196388,
    "user": {
      "login": "leyenda",
      "id": 394050,
      "avatar_url": "https://avatars1.githubusercontent.com/u/394050?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/leyenda",
      "html_url": "https://github.com/leyenda",
      "followers_url": "https://api.github.com/users/leyenda/followers",
      "following_url": "https://api.github.com/users/leyenda/following{/other_user}",
      "gists_url": "https://api.github.com/users/leyenda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/leyenda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/leyenda/subscriptions",
      "organizations_url": "https://api.github.com/users/leyenda/orgs",
      "repos_url": "https://api.github.com/users/leyenda/repos",
      "events_url": "https://api.github.com/users/leyenda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/leyenda/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-05-19T00:25:55Z",
    "updated_at": "2016-05-19T00:25:55Z",
    "body": "I've finally done it, it seems like a problem with XHR / JSONP polling transport. \nI am using   `electron 1.0.2` and `socket.io 1.4.6`\n\nJust specify in your client when setting the connection that you only want to use websockets.\n\n`var socket = require('socket.io-client')('http://localhost:5000', { transports: [ \"websocket\" ] });`\n\nHope this helps\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/220298483",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-220298483",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 220298483,
    "user": {
      "login": "andresmeidla",
      "id": 8395526,
      "avatar_url": "https://avatars1.githubusercontent.com/u/8395526?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/andresmeidla",
      "html_url": "https://github.com/andresmeidla",
      "followers_url": "https://api.github.com/users/andresmeidla/followers",
      "following_url": "https://api.github.com/users/andresmeidla/following{/other_user}",
      "gists_url": "https://api.github.com/users/andresmeidla/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/andresmeidla/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andresmeidla/subscriptions",
      "organizations_url": "https://api.github.com/users/andresmeidla/orgs",
      "repos_url": "https://api.github.com/users/andresmeidla/repos",
      "events_url": "https://api.github.com/users/andresmeidla/events{/privacy}",
      "received_events_url": "https://api.github.com/users/andresmeidla/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-05-19T11:31:51Z",
    "updated_at": "2016-05-19T11:31:51Z",
    "body": "Forcing it to use websockets as transport doesn't seem to be a solution (at least for me).\nI tried it a couple of days ago, and it seemed to work fine at first - client connected right away, messages got delivered etc.\nBut the error returned after some time (couple of hours and lots of connecting/disconnecting, appliance restarts).\nSo my guess is that all it did is change some internal timing so that it happened to succeed at first.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/232385094",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-232385094",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 232385094,
    "user": {
      "login": "darky",
      "id": 1832800,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1832800?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/darky",
      "html_url": "https://github.com/darky",
      "followers_url": "https://api.github.com/users/darky/followers",
      "following_url": "https://api.github.com/users/darky/following{/other_user}",
      "gists_url": "https://api.github.com/users/darky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/darky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/darky/subscriptions",
      "organizations_url": "https://api.github.com/users/darky/orgs",
      "repos_url": "https://api.github.com/users/darky/repos",
      "events_url": "https://api.github.com/users/darky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/darky/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-13T15:07:20Z",
    "updated_at": "2016-07-13T15:07:20Z",
    "body": "This issue affected on mongodb and elasticsearch too.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/232397603",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-232397603",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 232397603,
    "user": {
      "login": "darky",
      "id": 1832800,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1832800?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/darky",
      "html_url": "https://github.com/darky",
      "followers_url": "https://api.github.com/users/darky/followers",
      "following_url": "https://api.github.com/users/darky/following{/other_user}",
      "gists_url": "https://api.github.com/users/darky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/darky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/darky/subscriptions",
      "organizations_url": "https://api.github.com/users/darky/orgs",
      "repos_url": "https://api.github.com/users/darky/repos",
      "events_url": "https://api.github.com/users/darky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/darky/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-13T15:46:16Z",
    "updated_at": "2016-07-13T15:46:16Z",
    "body": "Also, I notice, timeout occured if using dnshostname instead ip. If indicate clearly ip, all fine.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/240045068",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-240045068",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 240045068,
    "user": {
      "login": "junedev",
      "id": 12543047,
      "avatar_url": "https://avatars0.githubusercontent.com/u/12543047?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/junedev",
      "html_url": "https://github.com/junedev",
      "followers_url": "https://api.github.com/users/junedev/followers",
      "following_url": "https://api.github.com/users/junedev/following{/other_user}",
      "gists_url": "https://api.github.com/users/junedev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/junedev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/junedev/subscriptions",
      "organizations_url": "https://api.github.com/users/junedev/orgs",
      "repos_url": "https://api.github.com/users/junedev/repos",
      "events_url": "https://api.github.com/users/junedev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/junedev/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-16T09:00:56Z",
    "updated_at": "2016-08-16T09:00:56Z",
    "body": "I am also affected by this (Ubuntu 15.10, electron-prebuilt 1.2.8, socket.io-client 1.4.8). I had the same experience as @andresmeidla, forcing websocket transport didn't fix it in the end. \nThanks to @darky! Switching from \"localhost\" to the ip seems to work for now, at least for testing locally.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/282116977",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-282116977",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 282116977,
    "user": {
      "login": "niftynei",
      "id": 1097769,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1097769?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/niftynei",
      "html_url": "https://github.com/niftynei",
      "followers_url": "https://api.github.com/users/niftynei/followers",
      "following_url": "https://api.github.com/users/niftynei/following{/other_user}",
      "gists_url": "https://api.github.com/users/niftynei/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/niftynei/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/niftynei/subscriptions",
      "organizations_url": "https://api.github.com/users/niftynei/orgs",
      "repos_url": "https://api.github.com/users/niftynei/repos",
      "events_url": "https://api.github.com/users/niftynei/events{/privacy}",
      "received_events_url": "https://api.github.com/users/niftynei/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-23T20:50:54Z",
    "updated_at": "2017-02-23T20:51:40Z",
    "body": "i'm experiencing this as well. Ubuntu 16.04 LTS, electron version 1.6.1. It happens for all /etc/hosts entries. Changing to the IP address (127.0.0.1) fixes the problem.\r\n\r\nI've tested other endpoints (non-local) and they work as expected.  This bug is unpredictable -- I've run electron apps on this computer for a while now without a problem.  I tried using strace to track down the problem -- shows \"-1 EACCESS Resource Not Available\".\r\n\r\nI haven't figured out a way to fix it. I'm planning to reboot my machine shortly.\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/284341538",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-284341538",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 284341538,
    "user": {
      "login": "notsyncing",
      "id": 2649806,
      "avatar_url": "https://avatars2.githubusercontent.com/u/2649806?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/notsyncing",
      "html_url": "https://github.com/notsyncing",
      "followers_url": "https://api.github.com/users/notsyncing/followers",
      "following_url": "https://api.github.com/users/notsyncing/following{/other_user}",
      "gists_url": "https://api.github.com/users/notsyncing/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/notsyncing/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/notsyncing/subscriptions",
      "organizations_url": "https://api.github.com/users/notsyncing/orgs",
      "repos_url": "https://api.github.com/users/notsyncing/repos",
      "events_url": "https://api.github.com/users/notsyncing/events{/privacy}",
      "received_events_url": "https://api.github.com/users/notsyncing/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-06T09:15:10Z",
    "updated_at": "2017-03-06T09:15:10Z",
    "body": "Same here on Ubuntu 16.10, electron 1.6.1, connecting to some port on `localhost` with http.request.\r\nThe request never finish, and no error was thrown.\r\nAs @niftynei said, change the `localhost` to `127.0.0.1` fixed the problem.\r\nThe same version of electron, on a macOS 10.12.3, does not affected by this problem."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/285986100",
    "html_url": "https://github.com/electron/electron/issues/1833#issuecomment-285986100",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/1833",
    "id": 285986100,
    "user": {
      "login": "janekolszak",
      "id": 3087849,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3087849?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/janekolszak",
      "html_url": "https://github.com/janekolszak",
      "followers_url": "https://api.github.com/users/janekolszak/followers",
      "following_url": "https://api.github.com/users/janekolszak/following{/other_user}",
      "gists_url": "https://api.github.com/users/janekolszak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/janekolszak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/janekolszak/subscriptions",
      "organizations_url": "https://api.github.com/users/janekolszak/orgs",
      "repos_url": "https://api.github.com/users/janekolszak/repos",
      "events_url": "https://api.github.com/users/janekolszak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/janekolszak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-12T23:19:46Z",
    "updated_at": "2017-03-12T23:19:46Z",
    "body": "I have the same problem: Ubuntu 16.04, electron 1.6.3 prerelease, using electron's `net` module"
  }
]