[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/136692219",
    "html_url": "https://github.com/electron/electron/issues/2583#issuecomment-136692219",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2583",
    "id": 136692219,
    "user": {
      "login": "iamdriz",
      "id": 801252,
      "avatar_url": "https://avatars0.githubusercontent.com/u/801252?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iamdriz",
      "html_url": "https://github.com/iamdriz",
      "followers_url": "https://api.github.com/users/iamdriz/followers",
      "following_url": "https://api.github.com/users/iamdriz/following{/other_user}",
      "gists_url": "https://api.github.com/users/iamdriz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iamdriz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iamdriz/subscriptions",
      "organizations_url": "https://api.github.com/users/iamdriz/orgs",
      "repos_url": "https://api.github.com/users/iamdriz/repos",
      "events_url": "https://api.github.com/users/iamdriz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iamdriz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-01T12:16:08Z",
    "updated_at": "2015-09-01T12:16:08Z",
    "body": "I've also noticed this when Electron applications crash or throw exception errors.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/138340281",
    "html_url": "https://github.com/electron/electron/issues/2583#issuecomment-138340281",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2583",
    "id": 138340281,
    "user": {
      "login": "iamdriz",
      "id": 801252,
      "avatar_url": "https://avatars0.githubusercontent.com/u/801252?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iamdriz",
      "html_url": "https://github.com/iamdriz",
      "followers_url": "https://api.github.com/users/iamdriz/followers",
      "following_url": "https://api.github.com/users/iamdriz/following{/other_user}",
      "gists_url": "https://api.github.com/users/iamdriz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iamdriz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iamdriz/subscriptions",
      "organizations_url": "https://api.github.com/users/iamdriz/orgs",
      "repos_url": "https://api.github.com/users/iamdriz/repos",
      "events_url": "https://api.github.com/users/iamdriz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iamdriz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-07T16:56:35Z",
    "updated_at": "2015-09-07T16:56:45Z",
    "body": "This issue also prevents the application from being open again until you manually close those left over processes.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/144373140",
    "html_url": "https://github.com/electron/electron/issues/2583#issuecomment-144373140",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2583",
    "id": 144373140,
    "user": {
      "login": "iamdriz",
      "id": 801252,
      "avatar_url": "https://avatars0.githubusercontent.com/u/801252?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iamdriz",
      "html_url": "https://github.com/iamdriz",
      "followers_url": "https://api.github.com/users/iamdriz/followers",
      "following_url": "https://api.github.com/users/iamdriz/following{/other_user}",
      "gists_url": "https://api.github.com/users/iamdriz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iamdriz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iamdriz/subscriptions",
      "organizations_url": "https://api.github.com/users/iamdriz/orgs",
      "repos_url": "https://api.github.com/users/iamdriz/repos",
      "events_url": "https://api.github.com/users/iamdriz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iamdriz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-30T11:49:37Z",
    "updated_at": "2015-09-30T11:49:37Z",
    "body": "@zcbenz What if the app unexpectedly quits or has an error that doesn't throw the invalid app error? The process is still left in these scenarios.\n"
  }
]