[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/155376368",
    "html_url": "https://github.com/electron/electron/pull/3368#issuecomment-155376368",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3368",
    "id": 155376368,
    "user": {
      "login": "romaincointepas",
      "id": 797899,
      "avatar_url": "https://avatars1.githubusercontent.com/u/797899?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/romaincointepas",
      "html_url": "https://github.com/romaincointepas",
      "followers_url": "https://api.github.com/users/romaincointepas/followers",
      "following_url": "https://api.github.com/users/romaincointepas/following{/other_user}",
      "gists_url": "https://api.github.com/users/romaincointepas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/romaincointepas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/romaincointepas/subscriptions",
      "organizations_url": "https://api.github.com/users/romaincointepas/orgs",
      "repos_url": "https://api.github.com/users/romaincointepas/repos",
      "events_url": "https://api.github.com/users/romaincointepas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/romaincointepas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-10T10:08:24Z",
    "updated_at": "2015-11-10T10:09:47Z",
    "body": "When I run:\n `./script/bootstrap.py --libcc_source_path=../libchromiumcontent/dist/main/src --libcc_shared_library_path=../libchromiumcontent/dist/main/shared_library --libcc_static_library_path=../libchromiumcontent/dist/main/static_library`\n\nI get the following error:\n\n```\nTraceback (most recent call last):\n  File \"/Users/romaincointepas/smartflix/electron/vendor/brightray/script/bootstrap\", line 97, in <module>\n    sys.exit(main())\n  File \"/Users/romaincointepas/smartflix/electron/vendor/brightray/script/bootstrap\", line 38, in main\n    args.libcc_static_library_path)\n  File \"/Users/romaincointepas/smartflix/electron/vendor/brightray/script/bootstrap\", line 85, in setup_libchromiumcontent\n    subprocess.check_call([sys.executable, download, '-s'] + args)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 535, in check_call\n    retcode = call(*popenargs, **kwargs)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 522, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 710, in __init__\n    errread, errwrite)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 1335, in _execute_child\n    raise child_exception\nTypeError: execv() arg 2 must contain only strings\n\nTraceback (most recent call last):\n  File \"./script/bootstrap.py\", line 233, in <module>\n    sys.exit(main())\n  File \"./script/bootstrap.py\", line 63, in main\n    args.libcc_static_library_path)\n  File \"./script/bootstrap.py\", line 144, in bootstrap_brightray\n    execute_stdout([sys.executable, bootstrap] + args)\n  File \"/Users/romaincointepas/smartflix/electron/script/lib/util.py\", line 178, in execute_stdout\n    execute(argv, env)\n  File \"/Users/romaincointepas/smartflix/electron/script/lib/util.py\", line 166, in execute\n    raise e\nsubprocess.CalledProcessError: Command '['/usr/bin/python', '/Users/romaincointepas/smartflix/electron/vendor/brightray/script/bootstrap', '--commit', '464aff2398f619b1d4d91b9187de69803919dca2', '--target_arch', 'x64', 'http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent', '--libcc_source_path', '../libchromiumcontent/dist/main/src', '--libcc_shared_library_path', '../libchromiumcontent/dist/main/shared_library', '--libcc_static_library_path', '../libchromiumcontent/dist/main/static_library']' returned non-zero exit status 1\n```\n\nNot sure about the error but what seems weird is that it is still calling the brightray bootstrap script with a commit hash and the URL?\n\nPS: I'm not confident that the command I'm running is the correct one (I guessed it from the commit but I'm pretty new to this).\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/155436256",
    "html_url": "https://github.com/electron/electron/pull/3368#issuecomment-155436256",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3368",
    "id": 155436256,
    "user": {
      "login": "tejaspathak",
      "id": 12093138,
      "avatar_url": "https://avatars2.githubusercontent.com/u/12093138?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tejaspathak",
      "html_url": "https://github.com/tejaspathak",
      "followers_url": "https://api.github.com/users/tejaspathak/followers",
      "following_url": "https://api.github.com/users/tejaspathak/following{/other_user}",
      "gists_url": "https://api.github.com/users/tejaspathak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tejaspathak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tejaspathak/subscriptions",
      "organizations_url": "https://api.github.com/users/tejaspathak/orgs",
      "repos_url": "https://api.github.com/users/tejaspathak/repos",
      "events_url": "https://api.github.com/users/tejaspathak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tejaspathak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-10T14:34:53Z",
    "updated_at": "2015-11-10T14:34:53Z",
    "body": "Can you please try the (change) [https://github.com/tejaspathak/brightray/commit/d4a9d15d054ebcea03f34a865417d5f009ffc4b9]\nand let us know ?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/155689727",
    "html_url": "https://github.com/electron/electron/pull/3368#issuecomment-155689727",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3368",
    "id": 155689727,
    "user": {
      "login": "romaincointepas",
      "id": 797899,
      "avatar_url": "https://avatars1.githubusercontent.com/u/797899?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/romaincointepas",
      "html_url": "https://github.com/romaincointepas",
      "followers_url": "https://api.github.com/users/romaincointepas/followers",
      "following_url": "https://api.github.com/users/romaincointepas/following{/other_user}",
      "gists_url": "https://api.github.com/users/romaincointepas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/romaincointepas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/romaincointepas/subscriptions",
      "organizations_url": "https://api.github.com/users/romaincointepas/orgs",
      "repos_url": "https://api.github.com/users/romaincointepas/repos",
      "events_url": "https://api.github.com/users/romaincointepas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/romaincointepas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T07:13:48Z",
    "updated_at": "2015-11-11T07:13:48Z",
    "body": "Same error :/\n\nI'm on OS X 10.11.1 with Xcode 7.1.1.\n\nI'm using master of each repo (with a merge of recent commits from libchromiumcontent/master to its atom branch).\n\nDid I use the new arguments correctly and pointed to the right folder? (I assume libcc source is dist/main/src, not libchromiumcontent repo?)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/155728092",
    "html_url": "https://github.com/electron/electron/pull/3368#issuecomment-155728092",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3368",
    "id": 155728092,
    "user": {
      "login": "tejaspathak",
      "id": 12093138,
      "avatar_url": "https://avatars2.githubusercontent.com/u/12093138?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tejaspathak",
      "html_url": "https://github.com/tejaspathak",
      "followers_url": "https://api.github.com/users/tejaspathak/followers",
      "following_url": "https://api.github.com/users/tejaspathak/following{/other_user}",
      "gists_url": "https://api.github.com/users/tejaspathak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tejaspathak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tejaspathak/subscriptions",
      "organizations_url": "https://api.github.com/users/tejaspathak/orgs",
      "repos_url": "https://api.github.com/users/tejaspathak/repos",
      "events_url": "https://api.github.com/users/tejaspathak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tejaspathak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T10:25:22Z",
    "updated_at": "2015-11-11T10:25:22Z",
    "body": "The change which i mentioned above [tejaspathak/brightray@d4a9d15] is not merged to main repo yet. I have generated pull request [https://github.com/atom/brightray/pull/174]  for it now. That should solve the below error that you are getting:\n\n```\nTypeError: execv() arg 2 must contain only strings\n```\n\npls make sure that you have manually applied above change or wait till it gets merged. libcc_source_path is the directory having component directory base, chrome, url, v8 etc. \n\nThe way I tested it was...\n1. Get the libchromiumcontent automatically without passing above options to bootstrap. \n2. Copy the directory electron/vendor/brightray/vendor/download/libchromiumcontent/ to lets say /Work/backup_libchromiumcontent\n3. Get new clone of electron or clean the existing one.\n4. Then pass foll. options to bootstrap. You might also want to pass -v for verbose messages\n\n```\n--libcc_source_path=/Work/backup_libchromiumcontent/src --libcc_shared_library_path=/Work/backup_libchromiumcontent/shared_library --libcc_static_library_path=/Work/backup_libchromiumcontent/static_library \n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/155736000",
    "html_url": "https://github.com/electron/electron/pull/3368#issuecomment-155736000",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3368",
    "id": 155736000,
    "user": {
      "login": "romaincointepas",
      "id": 797899,
      "avatar_url": "https://avatars1.githubusercontent.com/u/797899?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/romaincointepas",
      "html_url": "https://github.com/romaincointepas",
      "followers_url": "https://api.github.com/users/romaincointepas/followers",
      "following_url": "https://api.github.com/users/romaincointepas/following{/other_user}",
      "gists_url": "https://api.github.com/users/romaincointepas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/romaincointepas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/romaincointepas/subscriptions",
      "organizations_url": "https://api.github.com/users/romaincointepas/orgs",
      "repos_url": "https://api.github.com/users/romaincointepas/repos",
      "events_url": "https://api.github.com/users/romaincointepas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/romaincointepas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T10:57:18Z",
    "updated_at": "2015-11-11T10:57:18Z",
    "body": "Wow, sorry about that, it was late, I though it was merged already.\n\nIt fixed my problem, thanks!\n"
  }
]