[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/175563887",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-175563887",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 175563887,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-01-27T11:09:05Z",
    "updated_at": "2016-01-27T11:09:05Z",
    "body": "It looks very likely a problem of OS X, the file dialog should show like other apps.\n\nCan you try restarting your machine and see if it is still there?  \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/175762860",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-175762860",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 175762860,
    "user": {
      "login": "svileng",
      "id": 351592,
      "avatar_url": "https://avatars1.githubusercontent.com/u/351592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/svileng",
      "html_url": "https://github.com/svileng",
      "followers_url": "https://api.github.com/users/svileng/followers",
      "following_url": "https://api.github.com/users/svileng/following{/other_user}",
      "gists_url": "https://api.github.com/users/svileng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/svileng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/svileng/subscriptions",
      "organizations_url": "https://api.github.com/users/svileng/orgs",
      "repos_url": "https://api.github.com/users/svileng/repos",
      "events_url": "https://api.github.com/users/svileng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/svileng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-27T17:38:36Z",
    "updated_at": "2016-01-27T17:38:36Z",
    "body": "Restarted my machine, no effect. A colleague of mine ran the app (OSX `10.11.2`), and he doesn't experience that problem, which is well weird. Also, I do see certain icons for files, such as PNGs, but most file icons are also missing. I'm currently running OSX `10.11.3`.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/175927000",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-175927000",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 175927000,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-01-28T02:39:42Z",
    "updated_at": "2016-01-28T02:39:42Z",
    "body": "Does the file dialog in Chrome browser work correctly? What about other Electron apps like Atom or Visual Studio Code? \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/176281818",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-176281818",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 176281818,
    "user": {
      "login": "svileng",
      "id": 351592,
      "avatar_url": "https://avatars1.githubusercontent.com/u/351592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/svileng",
      "html_url": "https://github.com/svileng",
      "followers_url": "https://api.github.com/users/svileng/followers",
      "following_url": "https://api.github.com/users/svileng/following{/other_user}",
      "gists_url": "https://api.github.com/users/svileng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/svileng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/svileng/subscriptions",
      "organizations_url": "https://api.github.com/users/svileng/orgs",
      "repos_url": "https://api.github.com/users/svileng/repos",
      "events_url": "https://api.github.com/users/svileng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/svileng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-28T16:57:33Z",
    "updated_at": "2016-01-28T16:57:33Z",
    "body": "Both Chrome and Atom's file dialogs work normally.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/176513969",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-176513969",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 176513969,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-01-29T01:40:45Z",
    "updated_at": "2016-01-29T01:40:45Z",
    "body": "This makes the problem more strange, all of these apps are actually sharing the same dialog code.\n\nMaybe you can cleanup your project and do a complete rebuild, or try renaming your app to another name and see if the problem is still there.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/177752149",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-177752149",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 177752149,
    "user": {
      "login": "bengotow",
      "id": 1037212,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1037212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bengotow",
      "html_url": "https://github.com/bengotow",
      "followers_url": "https://api.github.com/users/bengotow/followers",
      "following_url": "https://api.github.com/users/bengotow/following{/other_user}",
      "gists_url": "https://api.github.com/users/bengotow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bengotow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bengotow/subscriptions",
      "organizations_url": "https://api.github.com/users/bengotow/orgs",
      "repos_url": "https://api.github.com/users/bengotow/repos",
      "events_url": "https://api.github.com/users/bengotow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bengotow/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-02-01T04:00:55Z",
    "updated_at": "2016-02-01T04:00:55Z",
    "body": "@jstejada was running into this a week or two ago as wellâ€”I remember we opened Console.app and there was a lot of noise coming from LaunchServices. Something to the effect of \"Can't establish XPC connection\". Do you see anything there?\n\nI think this must be a Mac OS X bug, but it's super interesting that it doesn't seem to impact other apps.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/177901304",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-177901304",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 177901304,
    "user": {
      "login": "svileng",
      "id": 351592,
      "avatar_url": "https://avatars1.githubusercontent.com/u/351592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/svileng",
      "html_url": "https://github.com/svileng",
      "followers_url": "https://api.github.com/users/svileng/followers",
      "following_url": "https://api.github.com/users/svileng/following{/other_user}",
      "gists_url": "https://api.github.com/users/svileng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/svileng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/svileng/subscriptions",
      "organizations_url": "https://api.github.com/users/svileng/orgs",
      "repos_url": "https://api.github.com/users/svileng/repos",
      "events_url": "https://api.github.com/users/svileng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/svileng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-02-01T10:32:54Z",
    "updated_at": "2016-02-01T10:32:54Z",
    "body": "@bengotow Yes, looks like I've got the same! I got about ~1100 of those when I clicked on a link that triggers the save file dialog:\n\n```\n01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database\n01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: Database mapping failed with result -10822, retrying\n01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database\n```\n\nAnd a bunch of those, as well as at the end of the logs:\n\n```\n01/02/2016 10:25:43.823 Electron[61351]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 \"connection to service named com.apple.iconservices\" UserInfo={NSDebugDescription=connection to service named com.apple.iconservices}\n01/02/2016 10:25:43.831 Electron[61351]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 \"connection to service named com.apple.iconservices\" UserInfo={NSDebugDescription=connection to service named com.apple.iconservices}\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/178743413",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-178743413",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 178743413,
    "user": {
      "login": "jstejada",
      "id": 1271509,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1271509?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jstejada",
      "html_url": "https://github.com/jstejada",
      "followers_url": "https://api.github.com/users/jstejada/followers",
      "following_url": "https://api.github.com/users/jstejada/following{/other_user}",
      "gists_url": "https://api.github.com/users/jstejada/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jstejada/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jstejada/subscriptions",
      "organizations_url": "https://api.github.com/users/jstejada/orgs",
      "repos_url": "https://api.github.com/users/jstejada/repos",
      "events_url": "https://api.github.com/users/jstejada/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jstejada/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-02-02T18:32:00Z",
    "updated_at": "2016-02-02T18:32:00Z",
    "body": "yes, I'm getting this error:\n\n```\nElectron[61018:6395526] Communications error: <OS_xpc_error: <error: 0x7fff7de7cc90> { count = 1, contents =\n        \"XPCErrorDescription\" => <string: 0x7fff7de7cf78> { length = 18, contents = \"Connection invalid\" }\n}>\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/209766459",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-209766459",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 209766459,
    "user": {
      "login": "ChrisPenner",
      "id": 6439644,
      "avatar_url": "https://avatars3.githubusercontent.com/u/6439644?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChrisPenner",
      "html_url": "https://github.com/ChrisPenner",
      "followers_url": "https://api.github.com/users/ChrisPenner/followers",
      "following_url": "https://api.github.com/users/ChrisPenner/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChrisPenner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChrisPenner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChrisPenner/subscriptions",
      "organizations_url": "https://api.github.com/users/ChrisPenner/orgs",
      "repos_url": "https://api.github.com/users/ChrisPenner/repos",
      "events_url": "https://api.github.com/users/ChrisPenner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChrisPenner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-14T05:18:03Z",
    "updated_at": "2016-04-14T05:18:03Z",
    "body": "I'm experiencing the same error:\n\n```\n2016-04-13 23:15:24.240 Electron[7123:3584536] Communications error: <OS_xpc_error: <error: 0x7fff75beec90> { count = 1, contents =\n        \"XPCErrorDescription\" => <string: 0x7fff75beef78> { length = 18, contents = \"Connection invalid\" }\n}>\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226434540",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-226434540",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 226434540,
    "user": {
      "login": "thomastuts",
      "id": 1914255,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1914255?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thomastuts",
      "html_url": "https://github.com/thomastuts",
      "followers_url": "https://api.github.com/users/thomastuts/followers",
      "following_url": "https://api.github.com/users/thomastuts/following{/other_user}",
      "gists_url": "https://api.github.com/users/thomastuts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thomastuts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thomastuts/subscriptions",
      "organizations_url": "https://api.github.com/users/thomastuts/orgs",
      "repos_url": "https://api.github.com/users/thomastuts/repos",
      "events_url": "https://api.github.com/users/thomastuts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thomastuts/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-16T09:27:35Z",
    "updated_at": "2016-06-16T09:27:35Z",
    "body": "Just wanted to chime in here and say that I have the same exact issue (also in open file dialogs). I'm also getting the XPC error (`connection invalid`).\n\nI'm using Node `6.1.0`, Electron `1.2.2` and OSX `10.11.5` if that's any help.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/229408889",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-229408889",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 229408889,
    "user": {
      "login": "matthewatabet",
      "id": 6320630,
      "avatar_url": "https://avatars2.githubusercontent.com/u/6320630?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matthewatabet",
      "html_url": "https://github.com/matthewatabet",
      "followers_url": "https://api.github.com/users/matthewatabet/followers",
      "following_url": "https://api.github.com/users/matthewatabet/following{/other_user}",
      "gists_url": "https://api.github.com/users/matthewatabet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matthewatabet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matthewatabet/subscriptions",
      "organizations_url": "https://api.github.com/users/matthewatabet/orgs",
      "repos_url": "https://api.github.com/users/matthewatabet/repos",
      "events_url": "https://api.github.com/users/matthewatabet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matthewatabet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-29T16:19:44Z",
    "updated_at": "2016-06-29T16:21:05Z",
    "body": "Same problem for me too.\n`2016-06-29 09:15:28.063 Electron[57773:4161280] Communications error: <OS_xpc_error: <error: 0x7fff7a2a9c90> { count = 1, contents =\n        \"XPCErrorDescription\" => <string: 0x7fff7a2a9f78> { length = 18, contents = \"Connection invalid\" }`\n\nOSX `10.11.2`\nNode `6.2.2`\nElectron `1.2.5`\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/239231338",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-239231338",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 239231338,
    "user": {
      "login": "inferno1005",
      "id": 160181,
      "avatar_url": "https://avatars1.githubusercontent.com/u/160181?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/inferno1005",
      "html_url": "https://github.com/inferno1005",
      "followers_url": "https://api.github.com/users/inferno1005/followers",
      "following_url": "https://api.github.com/users/inferno1005/following{/other_user}",
      "gists_url": "https://api.github.com/users/inferno1005/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/inferno1005/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/inferno1005/subscriptions",
      "organizations_url": "https://api.github.com/users/inferno1005/orgs",
      "repos_url": "https://api.github.com/users/inferno1005/repos",
      "events_url": "https://api.github.com/users/inferno1005/events{/privacy}",
      "received_events_url": "https://api.github.com/users/inferno1005/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-11T17:28:20Z",
    "updated_at": "2016-08-11T17:55:49Z",
    "body": "Was having the exact same issue with:\nOSX `10.11.3`\nNode `4.4.7`\nElectron `1.3.2`\n\nUpdated to:\nOSX `10.11.6` \n\nand the problem is not happening anymore!\n\n**edit**\n\nSo it turns out the problem was not fixed with upgrading. I know what is causing the issue in my environment however and it may help others.\n\nWhen launching the app in a tmux session the dialog window is messed up. When running in a normal shell session it works just fine. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/241014269",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-241014269",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 241014269,
    "user": {
      "login": "EllDoubleYew",
      "id": 7133050,
      "avatar_url": "https://avatars0.githubusercontent.com/u/7133050?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EllDoubleYew",
      "html_url": "https://github.com/EllDoubleYew",
      "followers_url": "https://api.github.com/users/EllDoubleYew/followers",
      "following_url": "https://api.github.com/users/EllDoubleYew/following{/other_user}",
      "gists_url": "https://api.github.com/users/EllDoubleYew/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EllDoubleYew/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EllDoubleYew/subscriptions",
      "organizations_url": "https://api.github.com/users/EllDoubleYew/orgs",
      "repos_url": "https://api.github.com/users/EllDoubleYew/repos",
      "events_url": "https://api.github.com/users/EllDoubleYew/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EllDoubleYew/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-19T13:11:45Z",
    "updated_at": "2016-08-19T13:14:07Z",
    "body": "I am running into this issue as well:\nOSX: `10.11.2`\nNode: `4.4.5`\nElectron: `1.2.5`\n\nIt has nothing to do with my file dialog but when I call my XHHTP requests. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/243535304",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-243535304",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 243535304,
    "user": {
      "login": "gammons",
      "id": 38560,
      "avatar_url": "https://avatars3.githubusercontent.com/u/38560?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gammons",
      "html_url": "https://github.com/gammons",
      "followers_url": "https://api.github.com/users/gammons/followers",
      "following_url": "https://api.github.com/users/gammons/following{/other_user}",
      "gists_url": "https://api.github.com/users/gammons/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gammons/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gammons/subscriptions",
      "organizations_url": "https://api.github.com/users/gammons/orgs",
      "repos_url": "https://api.github.com/users/gammons/repos",
      "events_url": "https://api.github.com/users/gammons/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gammons/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-30T18:31:00Z",
    "updated_at": "2016-08-30T18:31:00Z",
    "body": "What @inferno1005 said is correct!  I ran into this issue as well, and it turns out that running the electron app from within `tmux` was the issue.  \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/243881256",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-243881256",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 243881256,
    "user": {
      "login": "zeke",
      "id": 2289,
      "avatar_url": "https://avatars2.githubusercontent.com/u/2289?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zeke",
      "html_url": "https://github.com/zeke",
      "followers_url": "https://api.github.com/users/zeke/followers",
      "following_url": "https://api.github.com/users/zeke/following{/other_user}",
      "gists_url": "https://api.github.com/users/zeke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zeke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zeke/subscriptions",
      "organizations_url": "https://api.github.com/users/zeke/orgs",
      "repos_url": "https://api.github.com/users/zeke/repos",
      "events_url": "https://api.github.com/users/zeke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zeke/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-08-31T19:56:05Z",
    "updated_at": "2016-08-31T19:56:05Z",
    "body": "It sounds like running the app from `tmux` is the issue. @svileng are you also using `tmux`?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/255569948",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-255569948",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 255569948,
    "user": {
      "login": "jbeard4",
      "id": 586962,
      "avatar_url": "https://avatars1.githubusercontent.com/u/586962?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbeard4",
      "html_url": "https://github.com/jbeard4",
      "followers_url": "https://api.github.com/users/jbeard4/followers",
      "following_url": "https://api.github.com/users/jbeard4/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbeard4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbeard4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbeard4/subscriptions",
      "organizations_url": "https://api.github.com/users/jbeard4/orgs",
      "repos_url": "https://api.github.com/users/jbeard4/repos",
      "events_url": "https://api.github.com/users/jbeard4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbeard4/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-23T05:00:31Z",
    "updated_at": "2016-10-23T05:00:31Z",
    "body": "Confirmed this issue occurs for me when running electron from tmux. The problem is resolved when running the program outside of tmux.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/255698129",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-255698129",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 255698129,
    "user": {
      "login": "svileng",
      "id": 351592,
      "avatar_url": "https://avatars1.githubusercontent.com/u/351592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/svileng",
      "html_url": "https://github.com/svileng",
      "followers_url": "https://api.github.com/users/svileng/followers",
      "following_url": "https://api.github.com/users/svileng/following{/other_user}",
      "gists_url": "https://api.github.com/users/svileng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/svileng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/svileng/subscriptions",
      "organizations_url": "https://api.github.com/users/svileng/orgs",
      "repos_url": "https://api.github.com/users/svileng/repos",
      "events_url": "https://api.github.com/users/svileng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/svileng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-24T09:56:58Z",
    "updated_at": "2016-10-24T09:57:21Z",
    "body": "@zeke Yes, I do. I'm no longer working on that Electron project, so I cannot give it another go without tmux, unfortunately.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/306359240",
    "html_url": "https://github.com/electron/electron/issues/4236#issuecomment-306359240",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/4236",
    "id": 306359240,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-06-06T01:54:53Z",
    "updated_at": "2017-06-06T01:54:53Z",
    "body": "Running Electron from tmux has some [unintended behaviors](https://github.com/electron/electron/issues?q=is%3Aissue+tmux+is%3Aclosed), I'm not sure whether is a bug of tmux or macOS, but we are not able to fix it on Electron's side, and tmux is not designed to be run any GUI program inside at all. So I'm closing this as won't fix. "
  }
]