[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226079656",
    "html_url": "https://github.com/electron/electron/issues/6050#issuecomment-226079656",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6050",
    "id": 226079656,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-06-15T03:34:20Z",
    "updated_at": "2016-06-15T03:34:20Z",
    "body": "Can you add a `console.log` call in the callback to see whether the callback is executed at all?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226265957",
    "html_url": "https://github.com/electron/electron/issues/6050#issuecomment-226265957",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6050",
    "id": 226265957,
    "user": {
      "login": "mgparrish",
      "id": 15224223,
      "avatar_url": "https://avatars1.githubusercontent.com/u/15224223?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mgparrish",
      "html_url": "https://github.com/mgparrish",
      "followers_url": "https://api.github.com/users/mgparrish/followers",
      "following_url": "https://api.github.com/users/mgparrish/following{/other_user}",
      "gists_url": "https://api.github.com/users/mgparrish/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mgparrish/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mgparrish/subscriptions",
      "organizations_url": "https://api.github.com/users/mgparrish/orgs",
      "repos_url": "https://api.github.com/users/mgparrish/repos",
      "events_url": "https://api.github.com/users/mgparrish/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mgparrish/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-15T17:50:14Z",
    "updated_at": "2016-06-15T17:50:14Z",
    "body": "Thanks. I added the callback as you can see below. I updated the zip file \"FabricSaveCanvasBug.zip in the link above as well.\n\nWhen the error occurs the function \"saveCallback(filePath) is not executed. When the file is written successfully the console log indicates \"Callback Executed\".\n\nfunction saveTheFile(){\ndialog.showSaveDialog({title:'Testing a save dialog',defaultPath:'image.png'},saveCallback);\n}\n\nfunction saveCallback(filePath){\n\n// as a buffer\nvar buffer = canvasBuffer(canvas, 'image/png')\nconsole.log('Callback Executed'); //mgp added \n// write canvas to file\nfs.writeFile(filePath, buffer, function (err) {\n //throw err\n if(err)throw err;else console.log('Write of',filePath,'was successful');\n})\n\n}\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226390309",
    "html_url": "https://github.com/electron/electron/issues/6050#issuecomment-226390309",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6050",
    "id": 226390309,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-06-16T05:16:36Z",
    "updated_at": "2016-06-16T05:16:36Z",
    "body": "This turns out to be a bug of the `remote` object, thanks for providing the test case.\n"
  }
]