[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/229899602",
    "html_url": "https://github.com/electron/electron/pull/6309#issuecomment-229899602",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6309",
    "id": 229899602,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T09:19:14Z",
    "updated_at": "2016-07-01T09:19:14Z",
    "body": "Can we make the `setBadgeCount` API still fail silently but return `true` or `false` depending on success / failure.  This is consistant with quite a few of the other electron API's.\n\nIn regards to why, I know of an instance where an app (closed source) generates a badge count dynamically using `BrowserWindow.setIcon()` and using a canvas and a buffer to dynamically draw the numbers on an image.\n\nIt would be nice to use `setBadgeCount` but use the Buffer technique as a fall back\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/229941994",
    "html_url": "https://github.com/electron/electron/pull/6309#issuecomment-229941994",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6309",
    "id": 229941994,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-07-01T13:08:38Z",
    "updated_at": "2016-07-01T13:08:38Z",
    "body": "> Can we make the setBadgeCount API still fail silently but return true or false depending on success / failure. This is consistant with quite a few of the other electron API's.\n\nüëç \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/229948128",
    "html_url": "https://github.com/electron/electron/pull/6309#issuecomment-229948128",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6309",
    "id": 229948128,
    "user": {
      "login": "LinusU",
      "id": 189580,
      "avatar_url": "https://avatars3.githubusercontent.com/u/189580?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LinusU",
      "html_url": "https://github.com/LinusU",
      "followers_url": "https://api.github.com/users/LinusU/followers",
      "following_url": "https://api.github.com/users/LinusU/following{/other_user}",
      "gists_url": "https://api.github.com/users/LinusU/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LinusU/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LinusU/subscriptions",
      "organizations_url": "https://api.github.com/users/LinusU/orgs",
      "repos_url": "https://api.github.com/users/LinusU/repos",
      "events_url": "https://api.github.com/users/LinusU/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LinusU/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T13:35:51Z",
    "updated_at": "2016-07-01T13:35:51Z",
    "body": "Returning `false` when erroring feels very PHP. It's very easy for consumers to forget to wrap every call in `if (!theActuallCall()) throw new Error('...')`.\n\nIf you don't care about a particular error, isn't it better to try/catch?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/229953344",
    "html_url": "https://github.com/electron/electron/pull/6309#issuecomment-229953344",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6309",
    "id": 229953344,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T13:55:59Z",
    "updated_at": "2016-07-01T13:56:53Z",
    "body": "@LinusU It's what many other Electron methods do and it makes cross platform implementation a lot easier.  I shouldn't have to wrap all the partially supported electron API's in try { } catch { } just to stop errors.\n\nI.e. 99.99% of users would end up with code that looks like this\n\n``` js\ntry {\n    app.setBadgeCount(10);\n} catch (e) {\n    // Do nothing...\n}\n```\n\nIn this use case why would you want to throw an error if the call failed?\n"
  }
]