[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/230370540",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-230370540",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 230370540,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-07-05T01:30:43Z",
    "updated_at": "2016-07-05T01:30:43Z",
    "body": "Can you try whether 1.2.4 works?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/230977675",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-230977675",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 230977675,
    "user": {
      "login": "claygriffiths",
      "id": 375381,
      "avatar_url": "https://avatars2.githubusercontent.com/u/375381?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/claygriffiths",
      "html_url": "https://github.com/claygriffiths",
      "followers_url": "https://api.github.com/users/claygriffiths/followers",
      "following_url": "https://api.github.com/users/claygriffiths/following{/other_user}",
      "gists_url": "https://api.github.com/users/claygriffiths/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/claygriffiths/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/claygriffiths/subscriptions",
      "organizations_url": "https://api.github.com/users/claygriffiths/orgs",
      "repos_url": "https://api.github.com/users/claygriffiths/repos",
      "events_url": "https://api.github.com/users/claygriffiths/events{/privacy}",
      "received_events_url": "https://api.github.com/users/claygriffiths/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-07T04:41:26Z",
    "updated_at": "2016-07-07T04:41:26Z",
    "body": "I'm having the same problem as @ghego1. I'm usually seeing the following error:\n\n7/6/16 10:29:40.605 PM ShipIt[8038]: Installation error: Error Domain=NSPOSIXErrorDomain Code=13 \"Permission denied\" UserInfo={NSLocalizedDescription=Permission denied}\n\nThis search always shows issues popping up regarding non-admin accounts but I am on an admin account and this is happening even inside of my user directory.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/231329667",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-231329667",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 231329667,
    "user": {
      "login": "craigp",
      "id": 9042,
      "avatar_url": "https://avatars3.githubusercontent.com/u/9042?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/craigp",
      "html_url": "https://github.com/craigp",
      "followers_url": "https://api.github.com/users/craigp/followers",
      "following_url": "https://api.github.com/users/craigp/following{/other_user}",
      "gists_url": "https://api.github.com/users/craigp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/craigp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/craigp/subscriptions",
      "organizations_url": "https://api.github.com/users/craigp/orgs",
      "repos_url": "https://api.github.com/users/craigp/repos",
      "events_url": "https://api.github.com/users/craigp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/craigp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-08T10:39:45Z",
    "updated_at": "2016-07-08T10:39:45Z",
    "body": "> Can you try whether 1.2.4 works?\n\nI am having this problem on 1.2.5, but it does work properly in 1.2.4, I've just tried it.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/231330178",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-231330178",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 231330178,
    "user": {
      "login": "ghego1",
      "id": 4340360,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4340360?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghego1",
      "html_url": "https://github.com/ghego1",
      "followers_url": "https://api.github.com/users/ghego1/followers",
      "following_url": "https://api.github.com/users/ghego1/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghego1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghego1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghego1/subscriptions",
      "organizations_url": "https://api.github.com/users/ghego1/orgs",
      "repos_url": "https://api.github.com/users/ghego1/repos",
      "events_url": "https://api.github.com/users/ghego1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghego1/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-08T10:42:34Z",
    "updated_at": "2016-07-08T10:42:34Z",
    "body": "@craigp thanks for trying that, I did not had a chance to test it yet...\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/231345331",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-231345331",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 231345331,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-07-08T12:18:55Z",
    "updated_at": "2016-07-08T12:18:55Z",
    "body": "It seems to be related to the update of Squirrel.Mac. /cc @joshaber \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/231359697",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-231359697",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 231359697,
    "user": {
      "login": "joshaber",
      "id": 13760,
      "avatar_url": "https://avatars2.githubusercontent.com/u/13760?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joshaber",
      "html_url": "https://github.com/joshaber",
      "followers_url": "https://api.github.com/users/joshaber/followers",
      "following_url": "https://api.github.com/users/joshaber/following{/other_user}",
      "gists_url": "https://api.github.com/users/joshaber/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joshaber/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joshaber/subscriptions",
      "organizations_url": "https://api.github.com/users/joshaber/orgs",
      "repos_url": "https://api.github.com/users/joshaber/repos",
      "events_url": "https://api.github.com/users/joshaber/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joshaber/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-07-08T13:30:40Z",
    "updated_at": "2016-07-08T13:30:40Z",
    "body": "@craigp @ghego1 Let's try to find more logs. Go to `~/Library/Application Support/your-bundle-id.ShipIt` and `~/Library/Caches/your-bundle-id.ShipIt` and check out the logs in there.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/237419249",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-237419249",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 237419249,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-04T00:50:14Z",
    "updated_at": "2016-08-04T00:50:14Z",
    "body": "Having the same issue on OSX 10.11.5\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/237419463",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-237419463",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 237419463,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-04T00:51:38Z",
    "updated_at": "2016-08-04T00:51:38Z",
    "body": "There wasn't much log generated related to this as far as I can see. Though I do see an extracted app binary under ~/Library/Application Support/your-bundle.ShiptIt/updatexxxxx/\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/237421062",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-237421062",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 237421062,
    "user": {
      "login": "joshaber",
      "id": 13760,
      "avatar_url": "https://avatars2.githubusercontent.com/u/13760?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joshaber",
      "html_url": "https://github.com/joshaber",
      "followers_url": "https://api.github.com/users/joshaber/followers",
      "following_url": "https://api.github.com/users/joshaber/following{/other_user}",
      "gists_url": "https://api.github.com/users/joshaber/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joshaber/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joshaber/subscriptions",
      "organizations_url": "https://api.github.com/users/joshaber/orgs",
      "repos_url": "https://api.github.com/users/joshaber/repos",
      "events_url": "https://api.github.com/users/joshaber/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joshaber/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-08-04T01:02:16Z",
    "updated_at": "2016-08-04T01:02:16Z",
    "body": "Try updating to Electron 1.3+. If you're still seeing the problem, your logs should be in `~/Library/Caches/your-bundle.ShiptIt` (note that the location changed).\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/237982301",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-237982301",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 237982301,
    "user": {
      "login": "fravic",
      "id": 223553,
      "avatar_url": "https://avatars0.githubusercontent.com/u/223553?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fravic",
      "html_url": "https://github.com/fravic",
      "followers_url": "https://api.github.com/users/fravic/followers",
      "following_url": "https://api.github.com/users/fravic/following{/other_user}",
      "gists_url": "https://api.github.com/users/fravic/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fravic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fravic/subscriptions",
      "organizations_url": "https://api.github.com/users/fravic/orgs",
      "repos_url": "https://api.github.com/users/fravic/repos",
      "events_url": "https://api.github.com/users/fravic/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fravic/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-05T22:38:28Z",
    "updated_at": "2016-08-05T22:39:34Z",
    "body": "Also having the same problem with Electron 1.2.4, 1.2.8, and 1.3.2 on OS X 10.11.5.\n\nI'm seeing an error in the logs:\n\n```\nCouldn't remove owned bundle at location file:///var/folders/T/your-bundle.ShipIt/AppName.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: \"“AppName.app” couldn’t be removed.\", failureReason: \"The file doesn’t exist.\", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: \"The operation couldn’t be completed. No such file or directory\" }\n```\n\nBut it then says after that the `Installation completed successfully`, so I don't think it's relevant.\n\nMy updater code (based on https://nulab-inc.com/blog/typetalk/3-necessary-things-to-correctly-release-a-product-based-on-the-electron-app/):\n\n```\n  autoUpdater.setFeedURL(config.macUpdateUrl + '/' + appVersion);\n  autoUpdater.addListener('update-downloaded', function(e, releaseNotes, releaseName, releaseDate, updateURL, quitAndInstall) {\n    var index = dialog.showMessageBox(mainWindow, {\n      type: 'info',\n      buttons: ['Restart', 'Later'],\n      message: 'A new version is available! Please restart the app to apply the updates.',\n      detail: releaseName + \"\\n\\n\" + releaseNotes\n    });\n    if (index !== 1) {\n      quitAndInstall();\n    }\n  });\n  autoUpdater.checkForUpdates();\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/239193535",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-239193535",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 239193535,
    "user": {
      "login": "CyanCorsair",
      "id": 5261974,
      "avatar_url": "https://avatars0.githubusercontent.com/u/5261974?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CyanCorsair",
      "html_url": "https://github.com/CyanCorsair",
      "followers_url": "https://api.github.com/users/CyanCorsair/followers",
      "following_url": "https://api.github.com/users/CyanCorsair/following{/other_user}",
      "gists_url": "https://api.github.com/users/CyanCorsair/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CyanCorsair/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CyanCorsair/subscriptions",
      "organizations_url": "https://api.github.com/users/CyanCorsair/orgs",
      "repos_url": "https://api.github.com/users/CyanCorsair/repos",
      "events_url": "https://api.github.com/users/CyanCorsair/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CyanCorsair/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-11T15:18:27Z",
    "updated_at": "2016-08-11T15:22:28Z",
    "body": "I have a similar issue. The autoUpdater gets stuck at update-available on both Windows 7 and MacOS 10.10.5, Electron 1.3.2). It basically emits that [update-available] event - downloads the update, installs it - and then refuses to proceed. It will not, in any way, fire update-downloaded. The app is fully signed, I tried granting it the proper chown and chmod on Mac, kept it in the Application's folder like a regular user would. Nothing.\n\nI've been banging my head against this for the past 3 days. Any help? My ShipIt_Stderr.log outputs the same as the above: Couldn't remove owned bundle at location ... error NSError code 4, \"The File doesn't exist\".\n\nIf I then shut down the app and relaunch it, manually, it will have successfully updated, as ShipIt in its logs also report that \"Installation completed successfully\" - \"ShipIt quitting\". How can I provide my user with a good notification that they should restart, if the events do not propagate properly?\n\nCode:\n    `var platform = os.platform() + '_' + os.arch();\n    const version = app.getVersion(); // Current version of desktop app.\n    var feedURLEndPoint = 'update/' + platform + '/' + version;\n\n```\n// Set update source\nautoUpdater.setFeedURL('http://'HIDDEN URL'/' + feedURLEndPoint);\n\n// Let the UI know an update is available, and is being downloaded.\nautoUpdater.on('update-available', (event) => {\n  mainWindow.webContents.send('upc_broadcast', 'upc_found');\n});\n\n// Let UI know update had been downloaded. Prompt for restart.\nautoUpdater.on('update-downloaded', (event, releaseNotes, releaseName, releaseDate, updateURL, quitAndInstall) => {\n  mainWindow.webContents.send('info', 'upc_downloaded');\n});\n\n// TODO: Figure out proper exception handling on UI.\n// Send error message to frontend; refer to errorCollection obj in renderer.js for method params.\nautoUpdater.on('error', (err) => {\n  console.log(err.message);\n  mainWindow.webContents.send('upc_error', err.message);\n});\n\n// Let the UI know we're trying to find an update\n// Loading screen up by default\nautoUpdater.on('checking-for-update', (event) => {\n  mainWindow.webContents.send('upc_broadcast', 'upc_try');\n});\n\n// Let UI know there's no update. Kill loading screen.\nautoUpdater.on('update-not-available', () => {\n  mainWindow.webContents.send('upc_broadcast', 'upc_none');\n});\n\n// Check for updates\nmainWindow.webContents.once('did-frame-finish-load', (event) => {\n  autoUpdater.checkForUpdates();\n})\n\n// ipcMain receivers\nipc.on('upc_response', (event, arg) => {\n  if (arg.indexOf('confirm').indexOf !== -1)\n  {\n    // Invoked when they press \"Restart\" on the UI\n    autoUpdater.quitAndInstall();\n  }\n\n  if (arg.indexOf('deny').indexOf !== -1)\n  {\n    // In case they hit \"x\"?\n  }\n});`\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/242678743",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-242678743",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 242678743,
    "user": {
      "login": "cumajkeee",
      "id": 1834053,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1834053?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cumajkeee",
      "html_url": "https://github.com/cumajkeee",
      "followers_url": "https://api.github.com/users/cumajkeee/followers",
      "following_url": "https://api.github.com/users/cumajkeee/following{/other_user}",
      "gists_url": "https://api.github.com/users/cumajkeee/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cumajkeee/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cumajkeee/subscriptions",
      "organizations_url": "https://api.github.com/users/cumajkeee/orgs",
      "repos_url": "https://api.github.com/users/cumajkeee/repos",
      "events_url": "https://api.github.com/users/cumajkeee/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cumajkeee/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-26T09:28:28Z",
    "updated_at": "2016-08-26T09:30:24Z",
    "body": "Does anybody can confirm than problem solved in 1.3.3/4?\n\nIn 1.2.7 can confirm error in ShipIt/stderr.log with \"File not found\", and all process of auto update of application can finish with 3 results:\n1. Success: updated and app restarted\n2. Fail: app not updated but restarted (rear, but reproducible, all process of auto update passed well, except error with \"File not found\" which is not affect, as I understand, update process) \n3. Fail: app not updated and doesn't restarted (found once, not sure is it updater issue, that app doesn't restarted. Without it seems to be result n. 2)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/245718014",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-245718014",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 245718014,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-08T19:48:37Z",
    "updated_at": "2016-09-08T20:53:08Z",
    "body": "This still happens with 1.3.3\n\n```\n2016-09-08 11:00:59.620 ShipIt[14545:269605] Beginning installation\n2016-09-08 11:01:01.656 ShipIt[14545:269606] Moved bundle from file:///Applications/Cal.app to file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.joQfyCSY/Cal.app\n2016-09-08 11:01:01.656 ShipIt[14545:269606] Moved bundle from file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app to file:///Applications/Cal.app\n2016-09-08 11:01:01.690 ShipIt[14545:269606] Couldn't remove owned bundle at location file:///Users/zhenchao/Library/Caches/Cal.ShipIt/update.CC2zIay/Cal.app/, error NSError { domain: NSCocoaErrorDomain, code: 4, description: \"“Cal.app” couldn’t be removed.\", failureReason: \"The file doesn’t exist.\", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: \"The operation couldn’t be completed. No such file or directory\" }, userInfo: {\n    NSFilePath = \"/Users/zhenchao/Library/Caches/Cal.ShipIt/update.CC2zIay/Cal.app\";\n    NSUserStringVariant =     (\n        Remove\n    );\n} }\n2016-09-08 11:01:01.719 ShipIt[14545:269606] Couldn't remove owned bundle at location file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: \"“Cal.app” couldn’t be removed.\", failureReason: \"The file doesn’t exist.\", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: \"The operation couldn’t be completed. No such file or directory\" }, userInfo: {\n    NSFilePath = \"/var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app\";\n    NSUserStringVariant =     (\n        Remove\n    );\n} }\n2016-09-08 11:01:01.748 ShipIt[14545:269606] Installation completed successfully\n2016-09-08 11:01:01.748 ShipIt[14545:269606] ShipIt quitting\n```\n\nIt's probably not leaving enough info in the log file as to why it failed exactly.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/246002400",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-246002400",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 246002400,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-09T18:42:19Z",
    "updated_at": "2016-09-09T18:43:44Z",
    "body": "Hmm, some updates:\n\nThe app updated itself yesterday. I don't see any difference in logs. This is still updating from and to electron 1.3.3.\n\n@joshaber do you think it might have something to do with https://github.com/Squirrel/Squirrel.Mac/commit/413b1d2bca22e4c73d88989c40dbbe5d36c8e9c7 ?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/246935159",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-246935159",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 246935159,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-14T07:57:20Z",
    "updated_at": "2016-09-14T08:05:05Z",
    "body": "I'm having the same problem with 1.2.6, is this fixed in 1.3.5?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/246992060",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-246992060",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 246992060,
    "user": {
      "login": "joshaber",
      "id": 13760,
      "avatar_url": "https://avatars2.githubusercontent.com/u/13760?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joshaber",
      "html_url": "https://github.com/joshaber",
      "followers_url": "https://api.github.com/users/joshaber/followers",
      "following_url": "https://api.github.com/users/joshaber/following{/other_user}",
      "gists_url": "https://api.github.com/users/joshaber/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joshaber/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joshaber/subscriptions",
      "organizations_url": "https://api.github.com/users/joshaber/orgs",
      "repos_url": "https://api.github.com/users/joshaber/repos",
      "events_url": "https://api.github.com/users/joshaber/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joshaber/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-14T12:06:11Z",
    "updated_at": "2016-09-14T12:06:11Z",
    "body": "> @joshaber do you think it might have something to do with Squirrel/Squirrel.Mac@413b1d2 ?\n\nIt's certainly possible, but given that some folks are reporting it in 1.2.6 makes me think it's something else.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/247015967",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-247015967",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 247015967,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-14T13:40:39Z",
    "updated_at": "2016-09-14T13:40:39Z",
    "body": "We were using 1.2.6 for 2 months now and we got out few updates, everything worked perfectly, after the last OSX update the app has problems updating, i think this is related to Squirrel. See this issue regarding Squirrel logs:\nhttps://github.com/Squirrel/Squirrel.Mac/issues/181\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249146592",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-249146592",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 249146592,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-23T09:33:43Z",
    "updated_at": "2016-09-23T09:33:43Z",
    "body": "It seems the problem is that we changed the codesign certificate that has other identity, the updater fails to install the new certificate :)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249147697",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-249147697",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 249147697,
    "user": {
      "login": "ghego1",
      "id": 4340360,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4340360?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghego1",
      "html_url": "https://github.com/ghego1",
      "followers_url": "https://api.github.com/users/ghego1/followers",
      "following_url": "https://api.github.com/users/ghego1/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghego1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghego1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghego1/subscriptions",
      "organizations_url": "https://api.github.com/users/ghego1/orgs",
      "repos_url": "https://api.github.com/users/ghego1/repos",
      "events_url": "https://api.github.com/users/ghego1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghego1/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-23T09:39:24Z",
    "updated_at": "2016-09-23T09:39:24Z",
    "body": "In our case my feeling is that this issue is due to the fact that we build the app also with xcode (macgap). It has a different `bundle identifier`, but the app name and certificate used are the same.\nDoes this sound like a plausible cause?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249956575",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-249956575",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 249956575,
    "user": {
      "login": "danielsht86",
      "id": 6742833,
      "avatar_url": "https://avatars2.githubusercontent.com/u/6742833?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielsht86",
      "html_url": "https://github.com/danielsht86",
      "followers_url": "https://api.github.com/users/danielsht86/followers",
      "following_url": "https://api.github.com/users/danielsht86/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielsht86/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielsht86/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielsht86/subscriptions",
      "organizations_url": "https://api.github.com/users/danielsht86/orgs",
      "repos_url": "https://api.github.com/users/danielsht86/repos",
      "events_url": "https://api.github.com/users/danielsht86/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielsht86/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-27T18:36:04Z",
    "updated_at": "2016-09-27T18:36:04Z",
    "body": "Also running into this issue with Electron 1.4.0 and MacOS 10.12\n\nI am running as an Admin user and have installed the application in /Applications\n\nMy system.log is filled with these as some others have reported:\n\n```\nSep 27 11:29:02 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxConnect Client 0x7faa44f0a470-SketchMirrorHelper/NULL requesting attach to 0x176:55334 failed, no such device\nSep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxDictionary client 0x7faa44f0a470-SketchMirrorHelper/NULL using library 1, running usbmuxd-374.70\nSep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxConnect Client 0x7faa44f0a470-SketchMirrorHelper/NULL requesting attach to 0x176:55334 failed, no such device\nSep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.xpc.launchd[1] (ai.ark.arkIDE.ShipIt[57611]): Service could not initialize: 16A323: xpcproxy + 11769 [1475][625A730D-D6CA-3B26-ABFC-E0FD9005BAB6]: 0xd\nSep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.xpc.launchd[1] (ai.ark.arkIDE.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.\n```\n\nAlso ~/Library/Caches/ai.ark.arkIDE.ShipIt/ShipIt_stderr.log show the following, which was only logged the first time I attempted an update. This log is no longer being populated, most likely since  the service is crashing or not running\n\n```\n2016-09-22 13:47:07.820 ShipIt[12939:865137] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 \"Could not read update request\" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fda9e2012b0 {Error Domain=NSCocoaErrorDomain Code=260 \"The file “ShipItState.plist” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fda9e200560 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}}}\n2016-09-22 13:47:07.820 ShipIt[12939:865137] ShipIt quitting\n2016-09-22 13:47:09.852 ShipIt[12940:865177] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 \"Could not read update request\" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f80b65154f0 {Error Domain=NSCocoaErrorDomain Code=260 \"The file “ShipItState.plist” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f80b6513e60 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}}}\n2016-09-22 13:47:09.852 ShipIt[12940:865177] ShipIt quitting\n2016-09-22 13:47:11.892 ShipIt[12941:865223] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 \"Could not read update request\" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fae6db09b20 {Error Domain=NSCocoaErrorDomain Code=260 \"The file “ShipItState.plist” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fae6db0a8d0 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}}}\n2016-09-22 13:47:11.893 ShipIt[12941:865223] ShipIt quitting\n2016-09-22 13:47:13.928 ShipIt[12945:865311] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 \"Could not read update request\" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fea08500fe0 {Error Domain=NSCocoaErrorDomain Code=260 \"The file “ShipItState.plist” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fea08500e70 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}}}\n2016-09-22 13:47:13.928 ShipIt[12945:865311] ShipIt quitting\n2016-09-22 13:47:15.955 ShipIt[12946:865320] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 \"Could not read update request\" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f81c0f1e6b0 {Error Domain=NSCocoaErrorDomain Code=260 \"The file “ShipItState.plist” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f81c0f1cfe0 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}}}\n2016-09-22 13:47:15.955 ShipIt[12946:865320] ShipIt quitting\n```\n\nI can confirm that there is no file at `/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist`\n\nThis is not happening for everyone on our team. Any ideas/thoughts/clues?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249989850",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-249989850",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 249989850,
    "user": {
      "login": "danielsht86",
      "id": 6742833,
      "avatar_url": "https://avatars2.githubusercontent.com/u/6742833?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielsht86",
      "html_url": "https://github.com/danielsht86",
      "followers_url": "https://api.github.com/users/danielsht86/followers",
      "following_url": "https://api.github.com/users/danielsht86/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielsht86/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielsht86/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielsht86/subscriptions",
      "organizations_url": "https://api.github.com/users/danielsht86/orgs",
      "repos_url": "https://api.github.com/users/danielsht86/repos",
      "events_url": "https://api.github.com/users/danielsht86/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielsht86/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-27T20:34:18Z",
    "updated_at": "2016-09-27T20:34:18Z",
    "body": "Quick update: Deleting ~/Library/Caches/ai.ark.arkIDE.ShipIt and ~/Library/Caches/ai.ark.arkIDE and restarting fixed the issue. Not sure what caused it but hopefully this information is helpful to figuring out the root cause\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/261107523",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-261107523",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 261107523,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-16T23:34:25Z",
    "updated_at": "2016-11-16T23:34:25Z",
    "body": "The Electron version that came out today, 1.4.7, upgraded to Squirrel.Mac@0.3.0. Are people still experiencing this issue or has it gone away on 1.4.x? If you are still experiencing it, can you try 1.4.7 and see if it is working there? Thanks.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/271055970",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-271055970",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 271055970,
    "user": {
      "login": "nkt",
      "id": 3505878,
      "avatar_url": "https://avatars3.githubusercontent.com/u/3505878?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nkt",
      "html_url": "https://github.com/nkt",
      "followers_url": "https://api.github.com/users/nkt/followers",
      "following_url": "https://api.github.com/users/nkt/following{/other_user}",
      "gists_url": "https://api.github.com/users/nkt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nkt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nkt/subscriptions",
      "organizations_url": "https://api.github.com/users/nkt/orgs",
      "repos_url": "https://api.github.com/users/nkt/repos",
      "events_url": "https://api.github.com/users/nkt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nkt/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-07T02:18:49Z",
    "updated_at": "2017-01-07T02:20:01Z",
    "body": "Still present. Code:\r\n```js\r\nautoUpdater.on('update-downloaded', (event, notes, version) => {\r\n  const window = getAppWindow();\r\n  if (window) {\r\n    dialog.showMessageBox(window, {\r\n      type: 'question',\r\n      cancelId: 0,\r\n      defaultId: 1,\r\n      buttons: [\r\n        translator.translate('update_cancel'),\r\n        translator.translate('update_submit')\r\n      ],\r\n      message: translator.translate('update_question', { appName, notes, version })\r\n    }, (shouldUpdate) => {\r\n      if (shouldUpdate) {\r\n        autoUpdater.emit('quit-and-install');\r\n        autoUpdater.quitAndInstall();\r\n      } else {\r\n        autoCheck = false;\r\n      }\r\n    });\r\n  }\r\n});\r\n```\r\n\r\nAfter `quitAndInstall` call nothing happens. If I'm closing app using cmd+Q/quit in dock, app reopening with new version.\r\n\r\n```\r\n❯ electron --version\r\nv1.4.13\r\n```"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/273440758",
    "html_url": "https://github.com/electron/electron/issues/6345#issuecomment-273440758",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6345",
    "id": 273440758,
    "user": {
      "login": "stouch",
      "id": 17531455,
      "avatar_url": "https://avatars0.githubusercontent.com/u/17531455?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stouch",
      "html_url": "https://github.com/stouch",
      "followers_url": "https://api.github.com/users/stouch/followers",
      "following_url": "https://api.github.com/users/stouch/following{/other_user}",
      "gists_url": "https://api.github.com/users/stouch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stouch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stouch/subscriptions",
      "organizations_url": "https://api.github.com/users/stouch/orgs",
      "repos_url": "https://api.github.com/users/stouch/repos",
      "events_url": "https://api.github.com/users/stouch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stouch/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-18T10:34:01Z",
    "updated_at": "2017-01-18T10:44:14Z",
    "body": "I experience same problem as fantasticsid (8 Sep 2016).\r\n\r\n```\r\n2016-11-05 17:17:49.632 ShipIt[4132:2188928] Couldn't remove owned bundle at location file:///var/folders/sg/nh8znnm10hzg2h9tx75f21480000gn/T/BUNDLEID.ShipIt.nqdkAhGh/APPNAME.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: \"“APPNAME” couldn’t be removed.\", failureReason: \"The file doesn’t exist.\", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: \"The operation couldn’t be completed. No such file or directory\" }, userInfo: {\r\n    NSFilePath = \"/var/folders/sg/nh8znnm10hzg2h9tx75f21480000gn/T/BUNDLEID.ShipIt.nqdkAhGh/APPNAME.app\";\r\n    NSUserStringVariant =     (\r\n        Remove\r\n    );\r\n} }\r\n```\r\n\r\nI use Electron 1.4.8\r\n\r\nCode (called after update downloaded).\r\nMy app is just minimized but doesn't relaunch and I need to kill/launch it manually one or several times before it updates.\r\n\r\n```\r\n    autoUpdater.quitAndInstall()\r\n\r\n    // I tried this below : doesnt work either\r\n    setTimeout(function(){\r\n      app.relaunch({args: process.argv.slice(1).concat(['--relaunch'])})\r\n      app.exit(0)\r\n    },1000);\r\n\r\n```"
  }
]