[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/245026527",
    "html_url": "https://github.com/electron/electron/issues/7071#issuecomment-245026527",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7071",
    "id": 245026527,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-06T17:30:59Z",
    "updated_at": "2016-09-06T17:30:59Z",
    "body": "> lib-08805c6â€¦.js:10 Uncaught SyntaxError: Invalid regular expression: /^C:\\Users\\bcreel\\Documents\\Node\\muninn\\node_modules\\electron\\dist\\resources\\/: \\ at end of pattern\n\nAre you able to include the source from that line?\n\nIt looks like some code is trying to create a regular expression from an electron path and isn't properly escaping regex special characters that may exist in that path.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/245063756",
    "html_url": "https://github.com/electron/electron/issues/7071#issuecomment-245063756",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7071",
    "id": 245063756,
    "user": {
      "login": "scytalezero",
      "id": 704908,
      "avatar_url": "https://avatars1.githubusercontent.com/u/704908?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/scytalezero",
      "html_url": "https://github.com/scytalezero",
      "followers_url": "https://api.github.com/users/scytalezero/followers",
      "following_url": "https://api.github.com/users/scytalezero/following{/other_user}",
      "gists_url": "https://api.github.com/users/scytalezero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/scytalezero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/scytalezero/subscriptions",
      "organizations_url": "https://api.github.com/users/scytalezero/orgs",
      "repos_url": "https://api.github.com/users/scytalezero/repos",
      "events_url": "https://api.github.com/users/scytalezero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/scytalezero/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-06T19:34:04Z",
    "updated_at": "2016-09-06T19:34:04Z",
    "body": "Sure. I'm attaching a screenshot of the error source and the zipped source file:\n\n![2016-09-06 15_31_25-log in to apollo](https://cloud.githubusercontent.com/assets/704908/18287923/1b1655e4-7447-11e6-8b0e-d2105a1d170f.png)\n\n[lib-08805c69390428f6bd7f2e9c7c92214a.zip](https://github.com/electron/electron/files/457601/lib-08805c69390428f6bd7f2e9c7c92214a.zip)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/245075559",
    "html_url": "https://github.com/electron/electron/issues/7071#issuecomment-245075559",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7071",
    "id": 245075559,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-06T20:13:28Z",
    "updated_at": "2016-09-06T20:13:28Z",
    "body": "> Sure. I'm attaching a screenshot of the error source and the zipped source file:\n\nThe polyfill on that site for `String.prototype.startsWith` is definitely buggy. If you run `'\\\\'.startsWith('\\\\')` from the Console you'll see the same error.\n\nI don't think this an Electron issue but I'm not sure why the Electron version change would impact this polyfill coming into play.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/245091391",
    "html_url": "https://github.com/electron/electron/issues/7071#issuecomment-245091391",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7071",
    "id": 245091391,
    "user": {
      "login": "scytalezero",
      "id": 704908,
      "avatar_url": "https://avatars1.githubusercontent.com/u/704908?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/scytalezero",
      "html_url": "https://github.com/scytalezero",
      "followers_url": "https://api.github.com/users/scytalezero/followers",
      "following_url": "https://api.github.com/users/scytalezero/following{/other_user}",
      "gists_url": "https://api.github.com/users/scytalezero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/scytalezero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/scytalezero/subscriptions",
      "organizations_url": "https://api.github.com/users/scytalezero/orgs",
      "repos_url": "https://api.github.com/users/scytalezero/repos",
      "events_url": "https://api.github.com/users/scytalezero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/scytalezero/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-06T21:05:42Z",
    "updated_at": "2016-09-06T21:05:42Z",
    "body": "Gotcha. This does look to be some malfeasance on the part of the site. Thanks for checking it out!\n\nClosing this issue.\n"
  }
]