[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249699844",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249699844",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249699844,
    "user": {
      "login": "bengotow",
      "id": 1037212,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1037212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bengotow",
      "html_url": "https://github.com/bengotow",
      "followers_url": "https://api.github.com/users/bengotow/followers",
      "following_url": "https://api.github.com/users/bengotow/following{/other_user}",
      "gists_url": "https://api.github.com/users/bengotow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bengotow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bengotow/subscriptions",
      "organizations_url": "https://api.github.com/users/bengotow/orgs",
      "repos_url": "https://api.github.com/users/bengotow/repos",
      "events_url": "https://api.github.com/users/bengotow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bengotow/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-26T21:15:40Z",
    "updated_at": "2016-09-26T21:15:40Z",
    "body": "Hey! We're also seeing this when running the spec suite for N1. Seems to have just started happening in Electron 1.4.1.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249701423",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249701423",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249701423,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-26T21:22:10Z",
    "updated_at": "2016-09-26T21:22:10Z",
    "body": "Can confirm, I've been hitting this as well \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249701514",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249701514",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249701514,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-26T21:22:28Z",
    "updated_at": "2016-09-26T21:22:28Z",
    "body": "Woops, wrong button :(\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249702011",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249702011",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249702011,
    "user": {
      "login": "bengotow",
      "id": 1037212,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1037212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bengotow",
      "html_url": "https://github.com/bengotow",
      "followers_url": "https://api.github.com/users/bengotow/followers",
      "following_url": "https://api.github.com/users/bengotow/following{/other_user}",
      "gists_url": "https://api.github.com/users/bengotow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bengotow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bengotow/subscriptions",
      "organizations_url": "https://api.github.com/users/bengotow/orgs",
      "repos_url": "https://api.github.com/users/bengotow/repos",
      "events_url": "https://api.github.com/users/bengotow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bengotow/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-26T21:24:37Z",
    "updated_at": "2016-09-26T21:24:57Z",
    "body": "Looks like some sort of call to a cleaned-up object through `remote` — I wonder if it'd be a good idea to add `method` and `args` to these error messages so it'd be a bit easier to track down: https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L306\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249745733",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249745733",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249745733,
    "user": {
      "login": "jhgg",
      "id": 5489149,
      "avatar_url": "https://avatars0.githubusercontent.com/u/5489149?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jhgg",
      "html_url": "https://github.com/jhgg",
      "followers_url": "https://api.github.com/users/jhgg/followers",
      "following_url": "https://api.github.com/users/jhgg/following{/other_user}",
      "gists_url": "https://api.github.com/users/jhgg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jhgg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jhgg/subscriptions",
      "organizations_url": "https://api.github.com/users/jhgg/orgs",
      "repos_url": "https://api.github.com/users/jhgg/repos",
      "events_url": "https://api.github.com/users/jhgg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jhgg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-27T01:50:31Z",
    "updated_at": "2016-09-27T01:50:31Z",
    "body": "We're seeing this exact same exception too. Happens when we use ctrl + R to reload the app. \n\n```\nremote.js:176 Uncaught Error: Cannot read property 'object' of undefined\nTypeError: Cannot read property 'object' of undefined\n    at ObjectsRegistry.get (/Applications/Discord Canary.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)\n    at EventEmitter.<anonymous> (/Applications/Discord Canary.app/Contents/Resources/electron.asar/browser/rpc-server.js:305:31)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:201:7)\n    at WebContents.<anonymous> (/Applications/Discord Canary.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)\n    at emitTwo (events.js:106:13)\n    at WebContents.emit (events.js:191:7)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249915700",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249915700",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249915700,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-27T16:16:33Z",
    "updated_at": "2016-09-27T16:16:33Z",
    "body": "@paul321 @jhgg is this happening consistently or intermittently? Would it be possible to get the app you are seeing this on so I can try and debug it with a custom build? Thanks.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249998025",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249998025",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249998025,
    "user": {
      "login": "jhgg",
      "id": 5489149,
      "avatar_url": "https://avatars0.githubusercontent.com/u/5489149?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jhgg",
      "html_url": "https://github.com/jhgg",
      "followers_url": "https://api.github.com/users/jhgg/followers",
      "following_url": "https://api.github.com/users/jhgg/following{/other_user}",
      "gists_url": "https://api.github.com/users/jhgg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jhgg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jhgg/subscriptions",
      "organizations_url": "https://api.github.com/users/jhgg/orgs",
      "repos_url": "https://api.github.com/users/jhgg/repos",
      "events_url": "https://api.github.com/users/jhgg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jhgg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-27T21:03:46Z",
    "updated_at": "2016-09-27T21:03:53Z",
    "body": "Yeah. Just download Discord https://discordapp.com/download - pop open the inspector (cmd shift i) - hit ctrl - r a few times and it should happen. Definitely not seeing a 100% repro on it though. Sometimes it happens, others it doesn't. Sometimes hitting Ctrl+R again after the exception happens will cause it to refresh properly.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/249999208",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-249999208",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 249999208,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-27T21:08:12Z",
    "updated_at": "2016-09-27T21:08:12Z",
    "body": "@jhgg should I use the PTB version? Are you ever seeing it when refreshing the login screen or should I log in?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/250003889",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-250003889",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 250003889,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-09-27T21:26:01Z",
    "updated_at": "2016-09-27T21:26:01Z",
    "body": "I can reproduce this by running the `N1` test suite, the failing line is `remote.process.stdout.write(str)` in their spec runner.\n\nThis looks to happen intermittently when a `ELECTRON_BROWSER_DEREFERENCE` fires for the `stdout` property while it is being accessed.\n\nSo the order I'm seeing is:\n- `ELECTRON_BROWSER_MEMBER_GET` fires from renderer to main process for the `stdout` property.\n- The main process replies with the metadata information and the id of the object from the cache.\n- Before the renderer process receives the reply, a `ELECTRON_BROWSER_DEREFERENCE` fires for the `stdout` property clearing it from the cache.\n- When the renderer process receives the metadata and builds up the remote object, it is now using a cache id that is no longer present in the cache so the when `write` is called on the `stdout` remote property, it fails to obtain the `stdout` object from the object cache for the previously returned id.\n\nI can only reproduce this maybe once out of every 20 times tried so it seems to be dependent on a GC run happening at a specific time where the main process is building the metadata for the remote object and the renderer process runs the destructor for it.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/250061634",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-250061634",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 250061634,
    "user": {
      "login": "adamwoodnz",
      "id": 1017872,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1017872?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/adamwoodnz",
      "html_url": "https://github.com/adamwoodnz",
      "followers_url": "https://api.github.com/users/adamwoodnz/followers",
      "following_url": "https://api.github.com/users/adamwoodnz/following{/other_user}",
      "gists_url": "https://api.github.com/users/adamwoodnz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/adamwoodnz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/adamwoodnz/subscriptions",
      "organizations_url": "https://api.github.com/users/adamwoodnz/orgs",
      "repos_url": "https://api.github.com/users/adamwoodnz/repos",
      "events_url": "https://api.github.com/users/adamwoodnz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/adamwoodnz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-28T03:18:50Z",
    "updated_at": "2016-09-28T03:18:50Z",
    "body": "We're also getting this on 1.3.3\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/250069598",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-250069598",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 250069598,
    "user": {
      "login": "jhgg",
      "id": 5489149,
      "avatar_url": "https://avatars0.githubusercontent.com/u/5489149?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jhgg",
      "html_url": "https://github.com/jhgg",
      "followers_url": "https://api.github.com/users/jhgg/followers",
      "following_url": "https://api.github.com/users/jhgg/following{/other_user}",
      "gists_url": "https://api.github.com/users/jhgg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jhgg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jhgg/subscriptions",
      "organizations_url": "https://api.github.com/users/jhgg/orgs",
      "repos_url": "https://api.github.com/users/jhgg/repos",
      "events_url": "https://api.github.com/users/jhgg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jhgg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-09-28T04:36:06Z",
    "updated_at": "2016-09-28T04:36:06Z",
    "body": "@kevinsawicki both should work - they are on the same version of Electron now. Based on your findings above - I guess it'd only work when you log in and we start interfacing with remote objects.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/251050660",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-251050660",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 251050660,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-10-03T08:19:25Z",
    "updated_at": "2016-10-03T08:19:25Z",
    "body": "It seems that the reference chain is broken, `write` should reference `stdout`, it probably referenced `process` instead.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/251331639",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-251331639",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 251331639,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-10-04T08:53:32Z",
    "updated_at": "2016-10-04T08:53:32Z",
    "body": "I'm wondering whether we have met a bug of V8, for the `remote.process.stdout.write(str)` call, it works like this underlying:\n1. send `GLOBAL` message to get `process`\n2. send `MEMBER_GET` message to get `stdout` from `process`\n3. send `MEMBER_CALL` message to call `write` from `stdout`\n\nAnd the bug happens for either step 2) or 3), when `process` is garbage collected before `process.stdout` is called, or when `process.stdout` is garbage collected before `process.stdout.write` is called.\n\nSo for the expression `xxx.yyy`, it is possible that the `xxx` can be garbage collected when `xxx.yyy` is being called. This only happens when `yyy` is defined via `Object.defineProperty`.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252397726",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252397726",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252397726,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T02:41:56Z",
    "updated_at": "2016-10-08T02:41:56Z",
    "body": "so the workaround for now would be avoid remote calls and only use IPC messages?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252419362",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252419362",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252419362,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T11:23:15Z",
    "updated_at": "2016-10-08T11:23:26Z",
    "body": "@fantasticsid it seems that if the bug doesn't happen in the first second during webcontents load, it never happens later even if you use remote calls.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252421742",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252421742",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252421742,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T12:22:20Z",
    "updated_at": "2016-10-08T12:22:20Z",
    "body": "Yes when you load the app first time it doesn't happen, only after you\nrefresh it by using ctrl+r or cmd+r\n\nOn Oct 8, 2016 2:24 PM, \"Eugene Pankov\" notifications@github.com wrote:\n\n> @fantasticsid https://github.com/fantasticsid it seems that if the bug\n> doesn't happen in the first second during webcontents load, it never\n> happens later.\n> \n> —\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> https://github.com/electron/electron/issues/7351#issuecomment-252419362,\n> or mute the thread\n> https://github.com/notifications/unsubscribe-auth/AAh57szh7-OCOg5UhAYjBtEW9a1y3RGIks5qx31YgaJpZM4KGsBN\n> .\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252423017",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252423017",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252423017,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T12:50:48Z",
    "updated_at": "2016-10-08T12:50:48Z",
    "body": "In my case, ctrl-r actually \"fixes\" the issue, i.e. the app reloads without errors.\nSo in short, I have a ~10% chance of the abovementioned crash when [re]loading the app, but if it happens, reloading it again always helps.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252431116",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252431116",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252431116,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T15:39:26Z",
    "updated_at": "2016-10-08T15:39:26Z",
    "body": "Just the opposite case for me\n\nOn Oct 8, 2016 3:51 PM, \"Eugene Pankov\" notifications@github.com wrote:\n\n> In my case, ctrl-r actually \"fixes\" the issue, i.e. the app reloads\n> without errors.\n> So in short, I have a ~10% chance of the abovementioned crash when\n> [re]loading the app, but if it happens, reloading it again always helps.\n> \n> —\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> https://github.com/electron/electron/issues/7351#issuecomment-252423017,\n> or mute the thread\n> https://github.com/notifications/unsubscribe-auth/AAh57ngYYHzGaQ_dzkDLN8O_01OlMpjsks5qx5HbgaJpZM4KGsBN\n> .\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252434691",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252434691",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252434691,
    "user": {
      "login": "KochiyaOcean",
      "id": 8194131,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8194131?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/KochiyaOcean",
      "html_url": "https://github.com/KochiyaOcean",
      "followers_url": "https://api.github.com/users/KochiyaOcean/followers",
      "following_url": "https://api.github.com/users/KochiyaOcean/following{/other_user}",
      "gists_url": "https://api.github.com/users/KochiyaOcean/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/KochiyaOcean/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/KochiyaOcean/subscriptions",
      "organizations_url": "https://api.github.com/users/KochiyaOcean/orgs",
      "repos_url": "https://api.github.com/users/KochiyaOcean/repos",
      "events_url": "https://api.github.com/users/KochiyaOcean/events{/privacy}",
      "received_events_url": "https://api.github.com/users/KochiyaOcean/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-08T16:39:35Z",
    "updated_at": "2016-10-09T02:19:09Z",
    "body": "It sometimes occurs on a webview that have run several hours. All methods of webview (such as refresh, forward, getURL, etc) will return this Error\n\n![image](https://cloud.githubusercontent.com/assets/8194131/19217281/bfdf4ba4-8e09-11e6-8603-a62bcc9e4735.png)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252604309",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252604309",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252604309,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-10T12:27:49Z",
    "updated_at": "2016-10-10T12:27:49Z",
    "body": "@zcbenz not sure if I'm doing it right, but I tried to get and keep a global reference to `process` in the main process and `remote.process` in the renderer process to prevent them from being GCed, but it didn't help.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/252898730",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-252898730",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 252898730,
    "user": {
      "login": "vojtatranta",
      "id": 4154045,
      "avatar_url": "https://avatars3.githubusercontent.com/u/4154045?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vojtatranta",
      "html_url": "https://github.com/vojtatranta",
      "followers_url": "https://api.github.com/users/vojtatranta/followers",
      "following_url": "https://api.github.com/users/vojtatranta/following{/other_user}",
      "gists_url": "https://api.github.com/users/vojtatranta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vojtatranta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vojtatranta/subscriptions",
      "organizations_url": "https://api.github.com/users/vojtatranta/orgs",
      "repos_url": "https://api.github.com/users/vojtatranta/repos",
      "events_url": "https://api.github.com/users/vojtatranta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vojtatranta/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-11T12:05:57Z",
    "updated_at": "2016-10-11T12:05:57Z",
    "body": "Please please guy, our customers are very angry with this.\n\nCould you not just do something so that in would not throw such errors?\n\nThis line: https://github.com/electron/electron/blob/master/lib/browser/objects-registry.js#L44\n\nIs the root of the evil by itself. Yeah I know, there should be object with this id and it should have property `object` but apparantly. There is a bug?\n\nWhat if we just ifed it out and set logging there so we would know more? Thanks!\n\n@zcbenz thanks!\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/257653494",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-257653494",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 257653494,
    "user": {
      "login": "petrbrzek",
      "id": 879564,
      "avatar_url": "https://avatars0.githubusercontent.com/u/879564?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/petrbrzek",
      "html_url": "https://github.com/petrbrzek",
      "followers_url": "https://api.github.com/users/petrbrzek/followers",
      "following_url": "https://api.github.com/users/petrbrzek/following{/other_user}",
      "gists_url": "https://api.github.com/users/petrbrzek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/petrbrzek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/petrbrzek/subscriptions",
      "organizations_url": "https://api.github.com/users/petrbrzek/orgs",
      "repos_url": "https://api.github.com/users/petrbrzek/repos",
      "events_url": "https://api.github.com/users/petrbrzek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/petrbrzek/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-01T18:33:10Z",
    "updated_at": "2016-11-01T18:33:10Z",
    "body": "Any news about this one? \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/257662878",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-257662878",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 257662878,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-01T19:06:39Z",
    "updated_at": "2016-11-01T19:06:39Z",
    "body": "@vojtatranta ifing things  out will just make things worse in the future\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258091908",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258091908",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258091908,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T09:07:14Z",
    "updated_at": "2016-11-03T09:46:00Z",
    "body": "Any news?\nWe can't really use the latest builds of Electron\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258100034",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258100034",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258100034,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T09:50:46Z",
    "updated_at": "2016-11-03T09:50:46Z",
    "body": "@paul it seems to go away when running the production (i.e. built with electron-builder) version of my app. As for the development, I'm just restarting the app when it crashes :(\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258100298",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258100298",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258100298,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T09:52:06Z",
    "updated_at": "2016-11-03T09:52:06Z",
    "body": "@fantasticsid it's still better than the framework being unusable in some cases. Just if it out and spit out a warning instead. This way you can have working software AND fix it for real later.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258104809",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258104809",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258104809,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T10:13:39Z",
    "updated_at": "2016-11-03T10:13:39Z",
    "body": "In production you never get this error because the user never CTRL+R or CMD+R so there is no refresh :)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258105824",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258105824",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258105824,
    "user": {
      "login": "petrbrzek",
      "id": 879564,
      "avatar_url": "https://avatars0.githubusercontent.com/u/879564?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/petrbrzek",
      "html_url": "https://github.com/petrbrzek",
      "followers_url": "https://api.github.com/users/petrbrzek/followers",
      "following_url": "https://api.github.com/users/petrbrzek/following{/other_user}",
      "gists_url": "https://api.github.com/users/petrbrzek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/petrbrzek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/petrbrzek/subscriptions",
      "organizations_url": "https://api.github.com/users/petrbrzek/orgs",
      "repos_url": "https://api.github.com/users/petrbrzek/repos",
      "events_url": "https://api.github.com/users/petrbrzek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/petrbrzek/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T10:18:59Z",
    "updated_at": "2016-11-03T10:18:59Z",
    "body": "I wonder if this (https://github.com/paulcbetts/electron-remote) would help to prevent the issue. @paulcbetts \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258108057",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258108057",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258108057,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T10:30:44Z",
    "updated_at": "2016-11-03T10:30:44Z",
    "body": "@paul321 well, first, I do (own hotkey handler) and, second, the bug does also happen on the first app load sometimes.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258108450",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258108450",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258108450,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-03T10:32:43Z",
    "updated_at": "2016-11-03T18:38:12Z",
    "body": "So we are stuck on 1.2.6 because from 1.3.0+ Electron is useless for development :(\n\nOn Nov 3, 2016 12:31 PM, \"Eugene Pankov\" notifications@github.com wrote:\n\n> @paul321 https://github.com/paul321 well, first, I do (own hotkey\n> handler) and, second, the bug does also happen on the first app load\n> sometimes.\n> \n> —\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> https://github.com/electron/electron/issues/7351#issuecomment-258108057,\n> or mute the thread\n> https://github.com/notifications/unsubscribe-auth/AAh57om-2Mp_69k1EhHJ_Fkq0m0qhK50ks5q6bgNgaJpZM4KGsBN\n> .\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258458761",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258458761",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258458761,
    "user": {
      "login": "albertotagliavini",
      "id": 13029646,
      "avatar_url": "https://avatars0.githubusercontent.com/u/13029646?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/albertotagliavini",
      "html_url": "https://github.com/albertotagliavini",
      "followers_url": "https://api.github.com/users/albertotagliavini/followers",
      "following_url": "https://api.github.com/users/albertotagliavini/following{/other_user}",
      "gists_url": "https://api.github.com/users/albertotagliavini/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/albertotagliavini/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/albertotagliavini/subscriptions",
      "organizations_url": "https://api.github.com/users/albertotagliavini/orgs",
      "repos_url": "https://api.github.com/users/albertotagliavini/repos",
      "events_url": "https://api.github.com/users/albertotagliavini/events{/privacy}",
      "received_events_url": "https://api.github.com/users/albertotagliavini/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-04T15:15:07Z",
    "updated_at": "2016-11-04T16:14:13Z",
    "body": "In the piece of code that fails with this error, do you use the api remote.getGlobal(name) to call the remote function or you use the remote.require(module) api??\n\nBecause i have seen that changing the implementation, i'm getting no errors.\nBefore i had a module in global in the main process and i was obtaining it in the renderer process with remote.getGlobal(name) and sometimes i was getting the same error you are talking about.\n\nNow i have changed my code and i'm calling the remote module by remote.require(module).\nIt seems that i'm getting no errors.\nI'm using Electron 1.4.1\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/258492031",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-258492031",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 258492031,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-04T17:13:40Z",
    "updated_at": "2016-11-04T17:13:40Z",
    "body": "I'm using it this way:\nvar app = require('electron').remote.app;\n\nCan you give us an example from our perspective?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/260482207",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-260482207",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 260482207,
    "user": {
      "login": "qmphan",
      "id": 3208166,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3208166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/qmphan",
      "html_url": "https://github.com/qmphan",
      "followers_url": "https://api.github.com/users/qmphan/followers",
      "following_url": "https://api.github.com/users/qmphan/following{/other_user}",
      "gists_url": "https://api.github.com/users/qmphan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/qmphan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/qmphan/subscriptions",
      "organizations_url": "https://api.github.com/users/qmphan/orgs",
      "repos_url": "https://api.github.com/users/qmphan/repos",
      "events_url": "https://api.github.com/users/qmphan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/qmphan/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-14T22:20:40Z",
    "updated_at": "2016-11-14T22:29:01Z",
    "body": "I can reproduce this error with the following code:\n\n**main.js:**\n\n\"use strict\";\nlet { app, Menu, BrowserWindow } = require('electron');\nlet mainWindow = null;\nglobal['mytest'] = {'hello': 'world'};\nfunction createWindow() {\n    // Create the browser window.\n    var path = require('path');\n    mainWindow = new BrowserWindow({ width: 800, height: 600,\n        webPreferences: {\n            'preload': path.resolve(path.join(__dirname, 'preload.js')),\n            'nodeIntegration': true\n        }\n    });\n    mainWindow.loadURL(`http://www.google.com`);\n    mainWindow.loadURL(`http://www.google.com`); // Calling this line 2nd time causes the error\n    mainWindow.webContents.openDevTools();\n    mainWindow.on('closed', function () {\n        mainWindow = null;\n        app.quit();\n    });\n}\napp.on('ready', createWindow);\n\n**preload.js**\nprocess.once('loaded', () => {\n    const remote = require('electron').remote;\n    window.jsphone_api = remote.app.jsphone_api;\n    console.log('mytest = ', remote.getGlobal('mytest'));\n    console.log('preload got called');\n})\n- When I package it using electron-packager with option --arch=ia32 and run it on a 32bit Windows 7, this error happens every time. You can see in the log the message \"Cannot read property 'object' of undefined TypeError: Cannot read property 'object' of undefined...\". Note that the error happens because the function mainWindow.loadURL(`http://www.google.com`) is called twice. If I call it only once, there is no error.\n- When I run it on a 64 bit Windows 7 machine, there is no error.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/260732023",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-260732023",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 260732023,
    "user": {
      "login": "fantasticsid",
      "id": 203771,
      "avatar_url": "https://avatars0.githubusercontent.com/u/203771?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fantasticsid",
      "html_url": "https://github.com/fantasticsid",
      "followers_url": "https://api.github.com/users/fantasticsid/followers",
      "following_url": "https://api.github.com/users/fantasticsid/following{/other_user}",
      "gists_url": "https://api.github.com/users/fantasticsid/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fantasticsid/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fantasticsid/subscriptions",
      "organizations_url": "https://api.github.com/users/fantasticsid/orgs",
      "repos_url": "https://api.github.com/users/fantasticsid/repos",
      "events_url": "https://api.github.com/users/fantasticsid/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fantasticsid/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-15T18:54:50Z",
    "updated_at": "2016-11-15T18:54:50Z",
    "body": "@Eugeny silently swallowing the exception and expect your app to carry on IMHO is pretty bad.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/260739530",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-260739530",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 260739530,
    "user": {
      "login": "Eugeny",
      "id": 161476,
      "avatar_url": "https://avatars1.githubusercontent.com/u/161476?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eugeny",
      "html_url": "https://github.com/Eugeny",
      "followers_url": "https://api.github.com/users/Eugeny/followers",
      "following_url": "https://api.github.com/users/Eugeny/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eugeny/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eugeny/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eugeny/subscriptions",
      "organizations_url": "https://api.github.com/users/Eugeny/orgs",
      "repos_url": "https://api.github.com/users/Eugeny/repos",
      "events_url": "https://api.github.com/users/Eugeny/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eugeny/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-15T19:22:05Z",
    "updated_at": "2016-11-15T19:22:29Z",
    "body": "@fantasticsid absolutely. That's why I'm saying \"spit out a warning instead\" in my comment. That lets people carry on using Electron productively until this bug is fixed, without having to resort to patching Electron itself.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262331759",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262331759",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262331759,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T18:57:28Z",
    "updated_at": "2016-11-22T19:03:49Z",
    "body": "Any news on this one?\r\nA lot of production apps are crashing because of this bug."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262334075",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262334075",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262334075,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-22T19:05:41Z",
    "updated_at": "2016-11-22T19:05:41Z",
    "body": "> Any news on this one?\r\n\r\nThere haven't been any fixes for this yet, it is still being investigated to try and figure out why these objects are sometimes getting garbage collected and how Electron can prevent them from getting incorrectly destroyed.\r\n\r\n#8003 was merged and added custom error messages so you can now know specifically which methods, constructors, or properties are missing.\r\n\r\n> A lot of production apps are crashing because of this bug, it's ridiculous.\r\n\r\nThis bug shouldn't crash apps, it should only throw JavaScript errors in the render process. If you are seeing your app literally crash, please include a native crash report with the C++ stack trace and we can investigate it further.\r\n\r\nUntil this is issue is resolved, you can workaround this issue by using asynchronous IPC instead of the `remote` module for calling methods and transferring data between processes."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262334942",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262334942",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262334942,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T19:08:58Z",
    "updated_at": "2016-11-22T19:08:58Z",
    "body": "It's crashing only JS but the app will not work after the error was thrown, we are getting a lot of js errors after the first encounter and the app starts to throw other errors just like this one"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262335200",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262335200",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262335200,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T19:10:00Z",
    "updated_at": "2016-11-22T19:10:00Z",
    "body": "Thing is in our app we do not transfer any date between processes, the app it's only working on the render process"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262335528",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262335528",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262335528,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-22T19:11:16Z",
    "updated_at": "2016-11-22T19:11:16Z",
    "body": "@paul321 how many calls to the `remote` module is your app making? Are you able to switch them to use `ipcRenderer` until this issue is resolved? "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262336930",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262336930",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262336930,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T19:16:00Z",
    "updated_at": "2016-11-22T19:16:17Z",
    "body": "Just checked the source code, we have about 20 calls to remote like:\r\nremote,session\r\nremote.getCurrentWindow()\r\nremote.app\r\n...\r\n\r\nall of them are prefixed by require('electron')"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262337575",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262337575",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262337575,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-22T19:18:16Z",
    "updated_at": "2016-11-22T19:18:16Z",
    "body": "> Just checked the source code, we have about 20 calls to remote like:\r\n\r\nDo you know which specific ones are throwing this error?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262338163",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262338163",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262338163,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T19:20:28Z",
    "updated_at": "2016-11-22T19:20:28Z",
    "body": "nope, because we don't see which call throws the error from render process, we only see the error from main process and no stack trace"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262338670",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262338670",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262338670,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-22T19:22:24Z",
    "updated_at": "2016-11-22T19:22:24Z",
    "body": "> nope, because we don't see which call throws the error from render process, we only see the error from main process and no stack trace\r\n\r\nElectron 1.4.8 will be out later today and will contain better error messages for this bug. If you can re-run your app on that version you'll be able to know which remote calls are affected and you can then workaround them by using the `ipcRenderer` module until this issue is completely fixed."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262339583",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262339583",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262339583,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-22T19:25:56Z",
    "updated_at": "2016-11-22T19:25:56Z",
    "body": "Ok thank you, will keep you posted if i can get more info from 1.4.8"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262403412",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262403412",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262403412,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-23T00:06:44Z",
    "updated_at": "2016-11-23T00:06:44Z",
    "body": "> Ok thank you, will keep you posted if i can get more info from 1.4.8\r\n\r\n1.4.8 is now available."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262447590",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262447590",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262447590,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T07:19:49Z",
    "updated_at": "2016-11-23T07:20:05Z",
    "body": "Here is the error, call is made from this line\r\n```\r\nApp.win = require('electron').remote.getCurrentWindow();\r\n\r\nsetTimeout(function() {\r\n      App.win.show();\r\n}, 300);\r\n```\r\n\r\nUncaught Error: Cannot call function 'show' on missing remote object 10\r\nError: Cannot call function 'show' on missing remote object 10\r\n    at throwRPCError (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262449771",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262449771",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262449771,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T07:38:56Z",
    "updated_at": "2016-11-23T07:38:56Z",
    "body": "Another one\r\n\r\nUncaught (in promise) Error: Cannot call function 'getPath' on missing remote object 18\r\nError: Cannot call function 'getPath' on missing remote object 18\r\n    at throwRPCError (D:\\devel\\work\\js\\microstockr.desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at throwRPCError (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262455491",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262455491",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262455491,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T08:22:05Z",
    "updated_at": "2016-11-23T08:22:05Z",
    "body": "It seems i cannot call remote functions from render process, even if i put a break point at that line, dev tools console will show me that setProgressBar it's a function\r\n\r\n Uncaught (in promise) Error: Cannot call function 'setProgressBar' on missing remote object 41\r\nError: Cannot call function 'setProgressBar' on missing remote object 41\r\n    at throwRPCError (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at throwRPCError (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at metaToValue (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\renderer\\api\\remote.js:217:13)\r\n    at remoteMemberFunction (D:\\devel\\work\\js\\desktop\\node_modules\\electron-prebuilt\\dist\\resources\\electron.asar\\renderer\\api\\remote.js:113:18)"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262520350",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262520350",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262520350,
    "user": {
      "login": "Qquanwei",
      "id": 9263655,
      "avatar_url": "https://avatars0.githubusercontent.com/u/9263655?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Qquanwei",
      "html_url": "https://github.com/Qquanwei",
      "followers_url": "https://api.github.com/users/Qquanwei/followers",
      "following_url": "https://api.github.com/users/Qquanwei/following{/other_user}",
      "gists_url": "https://api.github.com/users/Qquanwei/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Qquanwei/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Qquanwei/subscriptions",
      "organizations_url": "https://api.github.com/users/Qquanwei/orgs",
      "repos_url": "https://api.github.com/users/Qquanwei/repos",
      "events_url": "https://api.github.com/users/Qquanwei/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Qquanwei/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T14:03:57Z",
    "updated_at": "2016-11-24T03:25:51Z",
    "body": "this problem occur for me , \r\n\r\nmy preload.js\r\n```\r\nwindow.pkg = require('electron').remote.require('./package.json');\r\n```\r\nthrow the same error when I access window.pkg \r\n\r\n\r\n-----------\r\n\r\nI'm using Lazy load can avoid this bug\r\n```\r\nwindow.getPkg = (function(){\r\n  let cache = null;\r\n  return function(){\r\n      if(!cache) cache = require('electron').remote.require('./package.json');\r\n      return cache;\r\n  }\r\n})()\r\n```\r\nI think load remote object can be safe after window load "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262590177",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262590177",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262590177,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T18:08:29Z",
    "updated_at": "2016-11-23T18:09:43Z",
    "body": "I'm using require js in a file like this one and keep a reference to remote objects but after few minutes the objects are not accessible anymore \r\n```\r\ndefine([\r\n    'moment',\r\n    'async',\r\n    'src/constants'\r\n], function(moment,async, Constants) {\r\n    return {\r\n        remote: require('electron').remote,\r\n        path: require('path'),\r\n        filesys: require('fs'),\r\n        app: require('electron').remote.app,\r\n\r\n        init: function() {\r\n            return this;\r\n        },\r\n     \r\n        thumbs: function() {\r\n            var self = this;\r\n            console.log(self.app.getPath('userData'));\r\n        }\r\n    }\r\n});\r\n```\r\n\r\nIn few minutes then function thumbs is called 'self.app.getPath' with throw an error"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/262924475",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-262924475",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 262924475,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-25T10:17:28Z",
    "updated_at": "2016-11-25T10:17:28Z",
    "body": "Even if i make the remote variables scope vars in thumbs function it's still crashing on CTRL + R or CMD+R"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/263030330",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-263030330",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 263030330,
    "user": {
      "login": "gewl",
      "id": 19766136,
      "avatar_url": "https://avatars3.githubusercontent.com/u/19766136?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gewl",
      "html_url": "https://github.com/gewl",
      "followers_url": "https://api.github.com/users/gewl/followers",
      "following_url": "https://api.github.com/users/gewl/following{/other_user}",
      "gists_url": "https://api.github.com/users/gewl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gewl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gewl/subscriptions",
      "organizations_url": "https://api.github.com/users/gewl/orgs",
      "repos_url": "https://api.github.com/users/gewl/repos",
      "events_url": "https://api.github.com/users/gewl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gewl/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-25T22:54:23Z",
    "updated_at": "2016-11-25T22:54:23Z",
    "body": "I've been getting what is (I believe) a related error. I'm using chentsulin's electron-react-boilerplate. Production and dev both work fine, but when I run a test I get this error from electron-json-storage:\r\n\r\n```\r\n[dirpath]/node_modules/electron-json-storage/lib/utils.js:30\r\nconst app = electron.app || electron.remote.app;\r\n^\r\n\r\nTypeError: Cannot read property 'app' of undefined\r\n```\r\n\r\nWould love any advice on how to fix this!"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/263033709",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-263033709",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 263033709,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-25T23:58:27Z",
    "updated_at": "2016-11-25T23:58:27Z",
    "body": "@gewl That's a different error. Looks like either your using tmux or your node_modules install is a bit messed up.  "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/263035255",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-263035255",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 263035255,
    "user": {
      "login": "gewl",
      "id": 19766136,
      "avatar_url": "https://avatars3.githubusercontent.com/u/19766136?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gewl",
      "html_url": "https://github.com/gewl",
      "followers_url": "https://api.github.com/users/gewl/followers",
      "following_url": "https://api.github.com/users/gewl/following{/other_user}",
      "gists_url": "https://api.github.com/users/gewl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gewl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gewl/subscriptions",
      "organizations_url": "https://api.github.com/users/gewl/orgs",
      "repos_url": "https://api.github.com/users/gewl/repos",
      "events_url": "https://api.github.com/users/gewl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gewl/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-26T00:29:14Z",
    "updated_at": "2016-11-26T00:29:14Z",
    "body": "Not using tmux! node_modules install may be messed up, but if so, this is the only place that it's creating any problems.\r\n\r\nI got it worked out. For future reference, (one possible) answer was to use electron-mocha instead of mocha in the test script. Thanks for the suggestions!"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/263425160",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-263425160",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 263425160,
    "user": {
      "login": "etyp",
      "id": 5808998,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5808998?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etyp",
      "html_url": "https://github.com/etyp",
      "followers_url": "https://api.github.com/users/etyp/followers",
      "following_url": "https://api.github.com/users/etyp/following{/other_user}",
      "gists_url": "https://api.github.com/users/etyp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etyp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etyp/subscriptions",
      "organizations_url": "https://api.github.com/users/etyp/orgs",
      "repos_url": "https://api.github.com/users/etyp/repos",
      "events_url": "https://api.github.com/users/etyp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etyp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-28T23:13:10Z",
    "updated_at": "2016-11-28T23:13:10Z",
    "body": "@kevinsawicki Please let us know if there's any specific information we can provide to help resolve this issue.\r\n\r\nI'm only seeing it on our Windows build now, but previously saw a lot of it on our users with OSX builds:\r\n- Electron versions: 1.4.1 and 1.3.9\r\n- OS: Windows 10\r\n\r\nError + stack:\r\n\r\n```\r\nError: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object> Error: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying er \r\nStack: \r\nError: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>\r\nError: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>\r\n    at callFunction (C:\\Users\\Redacted\\AppData\\Local\\Hive\\app-1.2.2\\resources\\electron.asar\\browser\\rpc-server.js:226:11)\r\n    at EventEmitter.<anonymous> (C:\\Users\\Redacted\\AppData\\Local\\Hive\\app-1.2.2\\resources\\electron.asar\\browser\\rpc-server.js:307:5)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (C:\\Users\\Redacted\\AppData\\Local\\Hive\\app-1.2.2\\resources\\electron.asar\\browser\\api\\web-contents.js:219:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at metaToValue (C:\\Users\\Redacted\\AppData\\Local\\Hive\\app-1.2.2\\resources\\electron.asar\\renderer\\api\\remote.js:210:13)\r\n    at remoteMemberFunction (C:\\Users\\Redacted\\AppData\\Local\\Hive\\app-1.2.2\\resources\\electron.asar\\renderer\\api\\remote.js:111:18)\r\n```\r\n\r\nI can also include our preload.js and usage of require if that helps."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/263428351",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-263428351",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 263428351,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-11-28T23:28:38Z",
    "updated_at": "2016-11-28T23:28:52Z",
    "body": "@etyp that stack you posted is a different error, not related to this issue.\r\n\r\n> Error processing argument at index 0, conversion failure from `#<Object>`\r\n\r\n\r\nIt looks like `setOverlayIcon` was called with a first argument of something other than a `NativeImage` instance."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265528552",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265528552",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265528552,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-12-07T18:23:02Z",
    "updated_at": "2016-12-07T18:23:02Z",
    "body": "Electron 1.4.11 and 1.3.13 are now out with a potential fix for this issue via #8110.\r\n\r\nCan people try updating to those versions and see if they can still reproduce this issue? Thanks."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265534937",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265534937",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265534937,
    "user": {
      "login": "Mic75",
      "id": 1568791,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1568791?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Mic75",
      "html_url": "https://github.com/Mic75",
      "followers_url": "https://api.github.com/users/Mic75/followers",
      "following_url": "https://api.github.com/users/Mic75/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mic75/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mic75/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mic75/subscriptions",
      "organizations_url": "https://api.github.com/users/Mic75/orgs",
      "repos_url": "https://api.github.com/users/Mic75/repos",
      "events_url": "https://api.github.com/users/Mic75/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mic75/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-07T18:45:53Z",
    "updated_at": "2016-12-07T18:45:53Z",
    "body": "On the project I am working on, we had the exception thrown from remote.js while refreshing the app (we were on 1.4.5 and we had to downgrade to 1.3.3).\r\n\r\nAfter upgrading to 1.4.11, no more exception thrown from remote.js, it looks like the issue is fixed !\r\nThank you sir !"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265548937",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265548937",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265548937,
    "user": {
      "login": "VINTproYKT",
      "id": 5708819,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5708819?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VINTproYKT",
      "html_url": "https://github.com/VINTproYKT",
      "followers_url": "https://api.github.com/users/VINTproYKT/followers",
      "following_url": "https://api.github.com/users/VINTproYKT/following{/other_user}",
      "gists_url": "https://api.github.com/users/VINTproYKT/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VINTproYKT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VINTproYKT/subscriptions",
      "organizations_url": "https://api.github.com/users/VINTproYKT/orgs",
      "repos_url": "https://api.github.com/users/VINTproYKT/repos",
      "events_url": "https://api.github.com/users/VINTproYKT/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VINTproYKT/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-07T19:33:57Z",
    "updated_at": "2016-12-07T19:33:57Z",
    "body": "@kevinsawicki This fixed *my* issue with disappearing remote objects. An interesting coincidence is that I have downloaded 1.4.10 three hours ago and got stuck with this problem. Now I'm all set, thank you! 👍"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265795229",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265795229",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265795229,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-12-08T17:06:20Z",
    "updated_at": "2016-12-08T17:06:20Z",
    "body": "@paul321 are you able to give the latest releases, 1.3.13 or 1.4.11, a try and see if you still experience this issue? Thanks."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265826499",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265826499",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265826499,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-08T19:09:55Z",
    "updated_at": "2016-12-08T19:09:55Z",
    "body": "I did try it today and it seems fixed :)\nThank you\n\nOn Dec 8, 2016 7:06 PM, \"Kevin Sawicki\" <notifications@github.com> wrote:\n\n> @paul321 <https://github.com/paul321> are you able to give the latest\n> releases, 1.3.13 or 1.4.11, a try and see if you still experience this\n> issue? Thanks.\n>\n> —\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/electron/electron/issues/7351#issuecomment-265795229>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAh57mjhfQoiCDeslcP7lAze0DnkLVERks5rGDkqgaJpZM4KGsBN>\n> .\n>\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/265830387",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-265830387",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 265830387,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-12-08T19:24:42Z",
    "updated_at": "2016-12-08T19:24:42Z",
    "body": "> I did try it today and it seems fixed :)\r\n\r\nThanks for confirming, will tentatively close this out, it if starts cropping up again we can reopen."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/266461788",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-266461788",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 266461788,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-12T15:34:34Z",
    "updated_at": "2016-12-12T15:34:34Z",
    "body": "I keep getting this error when i reload the application without restart\r\n\r\n\r\n\r\nremote.js:217 Uncaught Error: Cannot call function 'isVisible' on missing remote object 15\r\nError: Cannot call function 'isVisible' on missing remote object 15\r\n    at throwRPCError (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (/Users/Paul/Work/js/desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n\r\nFrom this piece of code:\r\n\r\n`\r\nvar win = require('electron').remote.getCurrentWindow();\r\nif(!win.isVisible()) {\r\n    win.show();\r\n}  \r\n`"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/266462164",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-266462164",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 266462164,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-12T15:35:53Z",
    "updated_at": "2016-12-12T15:35:53Z",
    "body": "and a lot of random remote errors like this one too:\r\n\r\nremote.js:217 Uncaught (in promise) Error: Cannot call function 'getSize' on missing remote object 26\r\nError: Cannot call function 'getSize' on missing remote object 26\r\n    at throwRPCError (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at throwRPCError (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at metaToValue (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)\r\n    at remoteMemberFunction (/Users/Paul/Work/js/microstockr.desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)\r\n\r\n`\r\nvar win = require('electron').remote.getCurrentWindow();\r\nvar size = win.getSize();\r\n`\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/266512852",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-266512852",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 266512852,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-12T18:36:13Z",
    "updated_at": "2016-12-12T18:36:13Z",
    "body": "Ok my mistake, i didn't updated Electron on this machine :)"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/275546751",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-275546751",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 275546751,
    "user": {
      "login": "etyp",
      "id": 5808998,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5808998?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etyp",
      "html_url": "https://github.com/etyp",
      "followers_url": "https://api.github.com/users/etyp/followers",
      "following_url": "https://api.github.com/users/etyp/following{/other_user}",
      "gists_url": "https://api.github.com/users/etyp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etyp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etyp/subscriptions",
      "organizations_url": "https://api.github.com/users/etyp/orgs",
      "repos_url": "https://api.github.com/users/etyp/repos",
      "events_url": "https://api.github.com/users/etyp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etyp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-26T23:28:41Z",
    "updated_at": "2017-01-26T23:29:17Z",
    "body": "Updated to Electron 1.4.14 about 2 weeks ago and our users are still seeing this issue @kevinsawicki . See the screenshot below that shows the stack + the Electron version:\r\n\r\n![missing-remote-screen](https://cloud.githubusercontent.com/assets/5808998/22354815/15f2d9a2-e3f5-11e6-99fd-e32d1aa0a5f2.png)\r\n\r\nAny idea how we can resolve in the short term? Also, is there any chance that something in their user data folder from an earlier, broken version is causing this to happen despite autoupdate moving them to a new version of Electron?\r\n\r\n(Note: this happens with \"platform\" and \"dock\" for us)\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276232384",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-276232384",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 276232384,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-01-31T00:04:22Z",
    "updated_at": "2017-01-31T00:04:22Z",
    "body": "> Any idea how we can resolve in the short term?\r\n\r\nCan you include the code running when the error is thrown?\r\n\r\n> Also, is there any chance that something in their user data folder from an earlier, broken version is causing this to happen despite autoupdate moving them to a new version of Electron?\r\n\r\nNo, if the console reports 1.4.14 then the update to that version has occurred."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/283148428",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-283148428",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 283148428,
    "user": {
      "login": "etyp",
      "id": 5808998,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5808998?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etyp",
      "html_url": "https://github.com/etyp",
      "followers_url": "https://api.github.com/users/etyp/followers",
      "following_url": "https://api.github.com/users/etyp/following{/other_user}",
      "gists_url": "https://api.github.com/users/etyp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etyp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etyp/subscriptions",
      "organizations_url": "https://api.github.com/users/etyp/orgs",
      "repos_url": "https://api.github.com/users/etyp/repos",
      "events_url": "https://api.github.com/users/etyp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etyp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-28T20:13:03Z",
    "updated_at": "2017-02-28T20:13:03Z",
    "body": "Sorry for the delay @kevinsawicki \r\n\r\nOn BrowserWindow instance, we use the `webPreferences.preload` option like so to avoid conflicting `require` statements:\r\n\r\n```\r\n// Main Process - main.js\r\n\r\nmainWindow = new BrowserWindow({\r\n    webPreferences: {\r\n      nodeIntegration: false,\r\n      preload: path.join(__dirname, 'preload.js')\r\n    }\r\n});\r\n```\r\n\r\nWhere preload.js is:\r\n\r\n```\r\n// preload.js\r\n\r\n// Use new namespace for require so that\r\n// other modules can use 'require' properly.\r\nDesktopRequire = require;\r\ndelete require;\r\n```\r\n\r\n\r\nAnd then on the renderer process (our web app), we define a Desktop object which hold references to select Electron modules like remote:\r\n\r\n```\r\n  // /some/fake/path/desktop.js\r\n\r\n  const isDesktop = /Electron/.test(navigator.userAgent) && typeof DesktopRequire !== 'undefined';\r\n  export const Desktop = isDesktop ? {} : false;\r\n  if (typeof DesktopRequire === 'undefined') {\r\n    DesktopRequire = function () { return function () { return false; }; };\r\n  }\r\n  // Keep a reference on the window\r\n  // [Attempt to avoid https://github.com/electron/electron/issues/7351]\r\n  window.Desktop = Desktop;\r\n  window.electron = {};\r\n\r\n  $(document).ready(() => {\r\n    window.electron = DesktopRequire('electron');\r\n    // ipc for talking to electron\r\n    Desktop.ipc = electron.ipcRenderer;\r\n    // Catch autoupdate errors\r\n    Desktop.ipc.on('autoUpdaterError', (error, message) => {\r\n      console.log(error);\r\n      console.log(message);\r\n    });\r\n    // remote for calling remote methods\r\n    Desktop.remote = electron.remote;\r\n    // Native Image\r\n    Desktop.nativeImage = electron.nativeImage;\r\n    const appVersion = Desktop.remote.app.getVersion();\r\n    const intAppVersion = parseInt(appVersion.replace(/\\./g, ''), 10);\r\n    // Dialog file system\r\n    Desktop.dialog = electron.remote.dialog;\r\n    // New browser windows\r\n    Desktop.window = electron.remote.getCurrentWindow();\r\n  });\r\n```\r\n\r\nFinally, we have an interval that calls this function with a certain number value to update the badge:\r\n\r\n```\r\n// /some/fake/path/set-badge.js\r\nimport { Desktop } from '/some/fake/path/desktop.js';\r\nexport const setBadge = (text) => {\r\n  const app = window.Desktop.remote.app || Desktop.remote.app;\r\n  const remote = window.Desktop.remote || Desktop.remote;\r\n  const nativeImage = remote.require('electron').nativeImage;\r\n\r\n  if (remote.process.platform === 'darwin') {\r\n    app.dock.setBadge('' + text);\r\n  } else if (remote.process.platform === 'win32') {\r\n    const win = remote.getCurrentWindow();\r\n\r\n    if (text === '') {\r\n      win.setOverlayIcon(null, '');\r\n      return;\r\n    }\r\n\r\n    // Create badge\r\n    const canvas = document.createElement('canvas');\r\n    canvas.height = 140;\r\n    canvas.width = 140;\r\n    const ctx = canvas.getContext('2d');\r\n    ctx.fillStyle = 'red';\r\n    ctx.beginPath();\r\n    ctx.ellipse(70, 70, 70, 70, 0, 0, 2 * Math.PI);\r\n    ctx.fill();\r\n    ctx.textAlign = 'center';\r\n    ctx.fillStyle = 'white';\r\n\r\n    if (text.length > 2) {\r\n      ctx.font = '75px sans-serif';\r\n      ctx.fillText('' + text, 70, 98);\r\n    } else if (text.length > 1) {\r\n      ctx.font = '100px sans-serif';\r\n      ctx.fillText('' + text, 70, 105);\r\n    } else {\r\n      ctx.font = '125px sans-serif';\r\n      ctx.fillText('' + text, 70, 112);\r\n    }\r\n\r\n    const badgeDataURL = canvas.toDataURL();\r\n    const img = nativeImage.createFromDataURL(badgeDataURL);\r\n\r\n    win.setOverlayIcon(img, text);\r\n  }\r\n};\r\n```\r\n\r\nWe used to not save the object to the `window`, but I added this in an attempt to keep `remote` from being dereferenced. I have a difficult time recreating locally, but we have dozens of users reporting it still happening, plus I see it from time to time.\r\n\r\nI'm going to try saving the `Desktop` object to global scope by not declaring `const | let | var` before it, but aside from that I'm unsure what to try.\r\n\r\nAny help would be absolutely amazing and much appreciated."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/283446018",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-283446018",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 283446018,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-01T19:38:06Z",
    "updated_at": "2017-03-01T19:38:06Z",
    "body": "We got the same problem when calling the function that is setting the badge icon from code\r\n\r\nUncaught (in promise) Error: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from 6\r\nError: Could not call remote function 'setOverlayIcon'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from 6\r\n\r\nIf we run the function from dev console like this App.setBadge('1') it's working find, called from other functions doesn't work"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/283461206",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-283461206",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 283461206,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-01T20:33:37Z",
    "updated_at": "2017-03-01T20:33:37Z",
    "body": "i think there is a problem setting the badge and i think someone should create a new ticket, check this out:\r\nhttp://stackoverflow.com/questions/41416052/nativeimage-not-working-in-setoverlayicon-in-electron"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/283467433",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-283467433",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 283467433,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-01T20:56:53Z",
    "updated_at": "2017-03-01T20:57:46Z",
    "body": "@etyp i found the error, if you send the text as an integer it's not working, and you will get that error, because in your  win.setOverlayIcon(img, text); the text var could be integer, try to to send text+''\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/285175763",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-285175763",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 285175763,
    "user": {
      "login": "etyp",
      "id": 5808998,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5808998?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etyp",
      "html_url": "https://github.com/etyp",
      "followers_url": "https://api.github.com/users/etyp/followers",
      "following_url": "https://api.github.com/users/etyp/following{/other_user}",
      "gists_url": "https://api.github.com/users/etyp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etyp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etyp/subscriptions",
      "organizations_url": "https://api.github.com/users/etyp/orgs",
      "repos_url": "https://api.github.com/users/etyp/repos",
      "events_url": "https://api.github.com/users/etyp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etyp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-08T21:31:01Z",
    "updated_at": "2017-03-08T21:31:01Z",
    "body": "@paul321 good find, but turns out it's not the issue we're encountering. We convert to string every time, plus we still see the error on Mac AND Windows, despite returning early from that function if on darwin.\r\n\r\nJust some of the recent errors thrown:\r\n\r\nOSX 10.9.5 sample:\r\n```\r\nError: Cannot get property 'dock' on missing remote object 4877\r\n```\r\n\r\nWindows 7 sample:\r\n```\r\nError: Cannot get property 'platform' on missing remote object 554\r\n```\r\n\r\nWindows 10 sample:\r\n```\r\nError: Cannot get property 'platform' on missing remote object 554\r\n```\r\n\r\nOSX 10.12.13 sample:\r\n```\r\nError: Cannot get property 'nativeImage' on missing remote object 343\r\n```\r\n\r\nOSX 10.12.3 sample:\r\n```\r\nError: Cannot get property 'dock' on missing remote object 12\r\n```\r\n\r\nOSX 10.12.3 sample:\r\n```\r\nError: Cannot get property 'platform' on missing remote object 76\r\n```\r\n\r\nIs anybody else that no longer encounters this using es6 modules?\r\n\r\nI know that imports are meant to keep 1 cached version in memory after the first time they're imported, but I'm worried something else is going wrong here (hence the saving references to `window.Whatever`)."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/287470243",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-287470243",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 287470243,
    "user": {
      "login": "etyp",
      "id": 5808998,
      "avatar_url": "https://avatars1.githubusercontent.com/u/5808998?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etyp",
      "html_url": "https://github.com/etyp",
      "followers_url": "https://api.github.com/users/etyp/followers",
      "following_url": "https://api.github.com/users/etyp/following{/other_user}",
      "gists_url": "https://api.github.com/users/etyp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etyp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etyp/subscriptions",
      "organizations_url": "https://api.github.com/users/etyp/orgs",
      "repos_url": "https://api.github.com/users/etyp/repos",
      "events_url": "https://api.github.com/users/etyp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etyp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-17T21:01:58Z",
    "updated_at": "2017-03-17T21:01:58Z",
    "body": "@kevinsawicki might this have anything to do with deleting the `require` reference on our preload script like this:\r\n\r\n```\r\n// preload.js\r\n\r\n// Use new namespace for require so that\r\n// other modules can use 'require' properly.\r\nDesktopRequire = require;\r\ndelete require;\r\n```"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/298686115",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-298686115",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 298686115,
    "user": {
      "login": "whmountains",
      "id": 8680147,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8680147?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/whmountains",
      "html_url": "https://github.com/whmountains",
      "followers_url": "https://api.github.com/users/whmountains/followers",
      "following_url": "https://api.github.com/users/whmountains/following{/other_user}",
      "gists_url": "https://api.github.com/users/whmountains/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/whmountains/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/whmountains/subscriptions",
      "organizations_url": "https://api.github.com/users/whmountains/orgs",
      "repos_url": "https://api.github.com/users/whmountains/repos",
      "events_url": "https://api.github.com/users/whmountains/events{/privacy}",
      "received_events_url": "https://api.github.com/users/whmountains/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-02T16:23:25Z",
    "updated_at": "2017-05-02T16:23:25Z",
    "body": "I get this error 100% of the time when running this example project: https://github.com/avocode/electron-windows-autoupdate.\r\n\r\n```\r\nUncaught Error: Could not call remote function 'setFeedURL'. Check that the function signature is correct. Underlying error: Could not get code signature for running application\r\nError: Could not call remote function 'setFeedURL'. Check that the function signature is correct. Underlying error: Could not get code signature for running application\r\n    at callFunction (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)\r\n    at EventEmitter.<anonymous> (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at callFunction (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)\r\n    at EventEmitter.<anonymous> (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n    at metaToValue (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)\r\n    at Object.remoteMemberFunction (/Users/mmc/code/electron-windows-autoupdate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)\r\n    at file:///Users/mmc/code/electron-windows-autoupdate/index.html:31:15\r\n```\r\n\r\nThe dependencies in that project are a bit out of date, but after updating everything I still get the same error.  I'm running Mac OS 10.12.4 Sierra, using Node v7.9.0, and installing packages with Yarn 0.22.0."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/298686503",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-298686503",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 298686503,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-05-02T16:24:54Z",
    "updated_at": "2017-05-02T16:24:54Z",
    "body": "> Could not get code signature for running application\r\n\r\n@whmountains Auto updating on macOS requires the application to be signed, that is why you are seeing this error."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/298687012",
    "html_url": "https://github.com/electron/electron/issues/7351#issuecomment-298687012",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/7351",
    "id": 298687012,
    "user": {
      "login": "whmountains",
      "id": 8680147,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8680147?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/whmountains",
      "html_url": "https://github.com/whmountains",
      "followers_url": "https://api.github.com/users/whmountains/followers",
      "following_url": "https://api.github.com/users/whmountains/following{/other_user}",
      "gists_url": "https://api.github.com/users/whmountains/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/whmountains/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/whmountains/subscriptions",
      "organizations_url": "https://api.github.com/users/whmountains/orgs",
      "repos_url": "https://api.github.com/users/whmountains/repos",
      "events_url": "https://api.github.com/users/whmountains/events{/privacy}",
      "received_events_url": "https://api.github.com/users/whmountains/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-02T16:26:49Z",
    "updated_at": "2017-05-02T16:26:49Z",
    "body": "@kevinsawicki Right, so this is a completely different error.  Sorry about that.\r\n\r\nI'm not going to delete my comment in case someone else searches that error message and finds this thread like I did.\r\n\r\n"
  }
]