[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/69461525",
    "html_url": "https://github.com/electron/electron/issues/998#issuecomment-69461525",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/998",
    "id": 69461525,
    "user": {
      "login": "cldwalker",
      "id": 11994,
      "avatar_url": "https://avatars3.githubusercontent.com/u/11994?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cldwalker",
      "html_url": "https://github.com/cldwalker",
      "followers_url": "https://api.github.com/users/cldwalker/followers",
      "following_url": "https://api.github.com/users/cldwalker/following{/other_user}",
      "gists_url": "https://api.github.com/users/cldwalker/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cldwalker/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cldwalker/subscriptions",
      "organizations_url": "https://api.github.com/users/cldwalker/orgs",
      "repos_url": "https://api.github.com/users/cldwalker/repos",
      "events_url": "https://api.github.com/users/cldwalker/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cldwalker/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-01-10T16:26:26Z",
    "updated_at": "2015-01-10T16:26:26Z",
    "body": "Confirmed that python 2.7.8 doesn't have this issue in this environment\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/69477064",
    "html_url": "https://github.com/electron/electron/issues/998#issuecomment-69477064",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/998",
    "id": 69477064,
    "user": {
      "login": "paulcbetts",
      "id": 1396,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1396?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulcbetts",
      "html_url": "https://github.com/paulcbetts",
      "followers_url": "https://api.github.com/users/paulcbetts/followers",
      "following_url": "https://api.github.com/users/paulcbetts/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulcbetts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulcbetts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulcbetts/subscriptions",
      "organizations_url": "https://api.github.com/users/paulcbetts/orgs",
      "repos_url": "https://api.github.com/users/paulcbetts/repos",
      "events_url": "https://api.github.com/users/paulcbetts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulcbetts/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-01-10T23:46:10Z",
    "updated_at": "2015-01-10T23:46:10Z",
    "body": "This is fixed in recent releases - the URL is now an `http` URL instead\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/69507290",
    "html_url": "https://github.com/electron/electron/issues/998#issuecomment-69507290",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/998",
    "id": 69507290,
    "user": {
      "login": "cldwalker",
      "id": 11994,
      "avatar_url": "https://avatars3.githubusercontent.com/u/11994?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cldwalker",
      "html_url": "https://github.com/cldwalker",
      "followers_url": "https://api.github.com/users/cldwalker/followers",
      "following_url": "https://api.github.com/users/cldwalker/following{/other_user}",
      "gists_url": "https://api.github.com/users/cldwalker/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cldwalker/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cldwalker/subscriptions",
      "organizations_url": "https://api.github.com/users/cldwalker/orgs",
      "repos_url": "https://api.github.com/users/cldwalker/repos",
      "events_url": "https://api.github.com/users/cldwalker/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cldwalker/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-01-11T19:27:57Z",
    "updated_at": "2015-01-11T22:09:19Z",
    "body": "@paulcbetts I see an https url [here](https://github.com/atom/atom-shell/blob/c8ed581e5c141b365b0a1e009ba908f13cf502ce/script/update-external-binaries.py#L12). I encountered this with 0.20.4. If you've verified this isn't an issue on master with latest python, feel free to close.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/69508579",
    "html_url": "https://github.com/electron/electron/issues/998#issuecomment-69508579",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/998",
    "id": 69508579,
    "user": {
      "login": "paulcbetts",
      "id": 1396,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1396?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulcbetts",
      "html_url": "https://github.com/paulcbetts",
      "followers_url": "https://api.github.com/users/paulcbetts/followers",
      "following_url": "https://api.github.com/users/paulcbetts/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulcbetts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulcbetts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulcbetts/subscriptions",
      "organizations_url": "https://api.github.com/users/paulcbetts/orgs",
      "repos_url": "https://api.github.com/users/paulcbetts/repos",
      "events_url": "https://api.github.com/users/paulcbetts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulcbetts/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-01-11T19:56:56Z",
    "updated_at": "2015-01-11T19:56:56Z",
    "body": "@cldwalker Oops, didn't look closely, that's another place that should be HTTP (or rather, new Python should ship an updated root cert list :-/)\n"
  }
]